load_board_description "baremetal-fpga-common"

set_board_cpu scr1

set_board_info memory,has_high_pa 0
set_board_info memory,ocd_work_area 0
set_board_info memory,reset_vector 0xffffff00

set_board_info ldscript "-T${testsuitedir}/boards/support/ldscripts/scr1.ld"

set_board_info openocd,flags [list \
 -f ${OPENOCD_ROOT}/share/openocd/scripts/interface/ftdi/digilent-hs2_fixed.cfg \
 -f ${testsuitedir}/boards/support/ocd/syntacore_riscv.cfg \
]
