load_board_description "baremetal-fpga-common"

set_board_cpu scr4_imcafd

set_board_info memory,has_high_pa 0
set_board_info memory,ocd_work_area 0
set_board_info memory,reset_vector 0xffffff00

set_board_info ldscript "-T${testsuitedir}/boards/support/ldscripts/scr4.ld"

set_board_info openocd,extra_csr 0
set_board_info openocd,hwthreads 0
set_board_info openocd,smp_target 0
set_board_info openocd,abi_regnames 0
set_board_info openocd,hidden_triggers 0
set_board_info openocd,ide_cloak 0

set_board_info openocd,interface_flags [list \
 -f ${OPENOCD_ROOT}/share/openocd/scripts/interface/ftdi/digilent-hs2a.cfg \
]
set_board_info openocd,ocd_tool_target_flags [list \
 -f ${testsuitedir}/boards/support/ocd/syntacore_score_nortos.cfg \
]
