set_board_info env,scripting_timeout 10
set_board_info env,preferred_timeout 15
set_board_info env,long_op_timeout 30
set_board_info env,resume_delay 0.1
set_board_info env,exec_delay 2

set_board_info env,ocdjtag_riscv_timeout 1
set_board_info env,ocdjtag_riscv_dmi_delay 0

proc jtag_tool_tap_definition_flags { tap_config { speed 500 } } {
  return [list \
    -f [get_support_file ocd/$tap_config] \
    -c "transport select jtag" \
    -c "adapter speed $speed"
  ]
}
