# this will cause config/sim.exp to be loaded at a later stage
load_generic_config "sim"

load_base_board_description "basic-sim"

set_board_info env,scripting_timeout 10
set_board_info env,preferred_timeout 10
set_board_info env,resume_delay 0.10
set_board_info env,exec_delay 0.10

set_board_info env,ocdjtag_riscv_timeout 1.0
set_board_info env,ocdjtag_riscv_dmi_delay 0

set_board_info memory,reset_vector 0x1000

set_board_info sim $SPIKE_SIM
add_board_info sim,options --rbb-port=$SPIKE_BITBANG

set_board_info ldscript "-T$testsuitedir/boards/support/ldscripts/spike.ld"

# NOTE: for now every spike configuration we use has only one TAP
# in general case this is not the case, so the code needs to be revised
set_board_info openocd,jtag_tool_tap_definition_flags \
  [list -f $testsuitedir/boards/support/ocd/jtag_1tap_irlen5.cfg]

proc ocd_tool_target_definition_flags { cfg_name } {
  global testsuitedir
  return [list \
    -f $testsuitedir/boards/support/ocd/$cfg_name \
  ]
}
