load_board_description "spike-sim-common"

set TGT_ARCH "rv32gc"
set_board_info cpu,xlen 32
set_board_info cpu,cores_num 1
set_board_info cpu,has_floats 1
set_board_info cpu,has_doubles 1
set_board_info memory,has_high_pa 0

add_board_info cflags   -march=$TGT_ARCH
add_board_info cflags   -mabi=ilp32d

set_board_info sim,options [subst [join { \
  "--rbb-port $SPIKE_BITBANG --isa $TGT_ARCH" \
  "--dm-progsize 6 --dm-sba 32 --dm-abstract-rti 0" \
} " "]]


