# this will cause config/sim.exp to be loaded at a later stage
load_generic_config "sim"

load_base_board_description "basic-sim"

set_board_info env,preferred_timeout 5
set_board_info env,resume_timeout 0.05
set_board_info env,exec_timeout 0.05

set_board_info memory,reset_vector 0x1000

set_board_info sim $SPIKE_SIM
add_board_info sim,options --rbb-port=$SPIKE_BITBANG

set_board_info ldscript "-T$testsuitedir/boards/support/ldscripts/spike.ld"

proc ocd_flags_for_spike { cfg_name } {
  global testsuitedir
  global SPIKE_BITBANG
  return [list \
    -c "gdb_port disabled ; telnet_port disabled" \
    -c "interface remote_bitbang" \
    -c "remote_bitbang host 127.0.0.1 ; remote_bitbang port $SPIKE_BITBANG" \
    -f "$testsuitedir/boards/support/ocd/$cfg_name" \
  ]
}
