load_board_description "spike-sim-common"

set_board_cpu spike64_dmp6a0 4

set_board_info memory,has_high_pa 0
set_board_info memory,ocd_work_area 0

set_board_info openocd,extra_csr 0
set_board_info openocd,hwthreads 0
set_board_info openocd,smp_target 0
set_board_info openocd,abi_regnames 0
set_board_info openocd,hidden_triggers 0
set_board_info openocd,ide_cloak 0

set_board_info openocd,ocd_tool_target_flags \
    [list -f [get_support_file ocd/spike_mcore4_rtoshw0.cfg]]
