# NOTE: we use standard.exp for two purposes:
# 1. set some common values for all boards (like ldflags)
# 2. provide some basic functionality to find support files and set board_cpu
# I'm not sure if the latter is the right way to do. Probably, this belongs
# to some other place.
proc get_support_file { filename } {
  global boards_dir
  # TODO: we should make sure that the requiested file is unique across
  # the whole chain.
  foreach bd [lreverse $boards_dir] {
    verbose "Searching $filename in $bd" 2
    set path_to_try [file join $bd support $filename]
    if {[file exists "$path_to_try"]} {
      verbose "Requested support file $filename found at $bd" 1
      return "$path_to_try"
    }
  }
  error "Could not find support file $filename"
}

proc set_board_cpu { cpu_name { harts_num 1} } {
  set cpu_def [get_support_file [file join cpu ${cpu_name}.exp]]
  verbose "Loading cpu: $cpu_name from $cpu_def" 1
  source $cpu_def

  set_board_info cpu,name $cpu_name
  set_board_info cpu,cores_num $harts_num
  add_board_info sim,options -p$harts_num
}

set_board_info ldflags "-nostdlib -nostartfiles"

set_board_info cflags "-nostdlib -nostartfiles"

set_board_info mathlib ""

