load_board_description "baremetal-fpga-common"

set_board_cpu scr7_2cpu

set_board_info memory,has_high_pa 0
set_board_info memory,ocd_work_area 0
set_board_info memory,reset_vector 0xffffffffffffff00

set_board_info ldscript "-T${testsuitedir}/boards/support/ldscripts/scr7.ld"

set_board_info openocd,extra_csr 0
set_board_info openocd,hwthreads 0
set_board_info openocd,smp_target 0
set_board_info openocd,abi_regnames 0
set_board_info openocd,hidden_triggers 0
set_board_info openocd,ide_cloak 0

set_board_info openocd,interface_flags [list \
 -f ${OPENOCD_ROOT}/share/openocd/scripts/interface/ftdi/digilent-hs2a.cfg \
]

set_board_info openocd,ocd_tool_target_flags [list \
 -f ${testsuitedir}/boards/support/ocd/syntacore_mcore2_nortos.cfg \
]

set_board_info openocd,jtag_tool_tap_definition_flags \
  [jtag_tool_tap_definition_flags jtag_2tap_irlen5.cfg]
