load_board_description "baremetal-fpga-common"

set TGT_ARCH "rv64gc"
add_board_info cpu,xlen 64
add_board_info cpu,cores_num 1
set_board_info cpu,has_floats 1
set_board_info cpu,has_doubles 1
set_board_info cpu,reset_vector 0xffffffffffffff00
set_board_info memory,has_high_pa 0

add_board_info cflags   "-march=$TGT_ARCH"

set_board_info ldscript "-T$testsuitedir/boards/support/ldscripts/scr7.ld"

set_board_info openocd,flags [subst [join [list \
 "-s ${OPENOCD_ROOT}/share/openocd/scripts" \
 "-f ${OPENOCD_ROOT}/share/openocd/scripts/interface/ftdi/digilent-hs2_fixed.cfg" \
 "-f ${OPENOCD_ROOT}/share/openocd/scripts/target/syntacore_riscv.cfg" \
] " "]]
