proc run_test {} {
  set VerboseLogFile [utils_spawn_universal_launcher \
    [list --verbose --run-command shutdown] \
    verbose  \
    expect_success]
  set NormalLogFile [utils_spawn_universal_launcher \
    [list --run-command shutdown] \
    no_verbose  \
    expect_success]

  exec grep --text -m 1 -E "^Debug:" $VerboseLogFile
  exec grep --text -m 1 -E "^Info :" $VerboseLogFile

  exec grep --text -m 1 -E "^Info :" $NormalLogFile
  if {![catch { exec grep -m 1 -E "^Debug :" $NormalLogFile } result]} {
    error "Unexpected Debug: log pattern found"
  }
  return [ocd_test_pass]
}

return [run_test]
