proc run_test {} {
  set SavedConfig [tool_state_get default_bin_prefix]_saved.cfg
  set SaveLogFile [utils_spawn_universal_launcher \
    [list --save $SavedConfig --run-command shutdown] \
    save \
    expect_success]
  if {![file exists $SavedConfig]} {
    error "could not detect a saved configuration file at $SavedConfig"
  }

  set LoadLogFile [utils_spawn_universal_launcher \
    [list --load $SavedConfig --run-command shutdown] \
    load \
    expect_success]
  set LoadLogFile2 [utils_spawn_universal_launcher \
    [list --debug-adapter-serial "" --load $SavedConfig --run-command shutdown] \
    load \
    expect_success]

  set SecondSaved "${SavedConfig}2"
  set SaveLoadLogFile [utils_spawn_universal_launcher \
    [list --save "${SecondSaved}" --load $SavedConfig --run-command shutdown] \
    save_load \
    expect_success]
  if {![file exists "${SecondSaved}"]} {
    error "could not detect a saved configuration file at $SecondSaved"
  }

  set CouldNotSaveLogFile [utils_spawn_universal_launcher \
    [list --save /tmp/valjalsdjsald/non_existent] \
    could_not_save \
    expect_failure]
  exec grep --text -F "Error: could not save adapter information" $CouldNotSaveLogFile

  if {[target_info sim] ne ""} {
    return [ocd_test_pass]
  }

  set NonExistentConfig /tmp/valjalsdjsald/non_existent
  set CouldNotLoadLogFile [utils_spawn_universal_launcher \
    [list --load $NonExistentConfig] could_not_load expect_failure]

  # Note: loading of configuration file is supported only for non-spike targets
  exec grep --text -F "adapter information loaded from $SavedConfig" $LoadLogFile
  exec grep --text -F "adapter information loaded from $SavedConfig" $LoadLogFile2
  exec grep --text -F "adapter information loaded from $SavedConfig" $SaveLoadLogFile

  exec grep --text -F "Error: could not load adapter info from $NonExistentConfig" $CouldNotLoadLogFile
  return [ocd_test_pass]
}

return [run_test]
