proc run_test {} {
  # NOTE: if target is a simulator - this test is unsupported
  if {[target_info sim] ne ""} {
    return [ocd_test_unsupported]
  }

  set LogFileAbsolute [utils_spawn_universal_launcher \
    [list --i-know-what-im-doing "[standInfoGet adapter_config]" --run-command shutdown] \
    i-know-better-relative \
    expect_success]

  set LogsToCheck [list $LogFileAbsolute]

  if { [standInfoGet adapter_config_relative] ne "" } {
    set LogFileRelative [utils_spawn_universal_launcher \
      [list --i-know-what-im-doing "[standInfoGet adapter_config_relative]" --run-command shutdown] \
      i-know-better-absolute \
      expect_success]
    lappend LogsToCheck $LogFileRelative
  }

  foreach Log $LogsToCheck {
    exec grep --text -F "Target successfully examined" $Log
    exec grep --text -F "Listening on port 3333 for gdb connections" $Log
  }

  set LogFileErrInteractive [utils_spawn_universal_launcher \
    [list --i-know-what-im-doing - --disable-interactive-mode] \
    i-know-better-err-interactive   expect_failure]
  set ExpectedErrMessage "Error: interactive mode disabled, while interactive config specification requested"
  exec grep --text -F "$ExpectedErrMessage" $LogFileErrInteractive

  return [ocd_test_pass]
}

return [run_test]
