proc expectExpr { spawn_id expr reason } {
  expect {
    -ex $expr {
    }
    eof {
      set EofResult [wait]
      error "unexpected termination while waiting for $reason ($EofResult)"
    }
    timeout {
      close
      wait
      error "unexpected timeout while waiting for $reason"
    }
  }
}

proc expectTelnetStartup { spawn_id } {
  expectExpr $spawn_id "Target successfully examined" "target examine"
  expectExpr $spawn_id "Open On-Chip Debugger" "telnet signature"
  expectExpr $spawn_id "\r\n\r>" "telnet prompt"
}

proc expectTelnetTargetListing { spawn_id } {
  send "targets\n"
  expectExpr $spawn_id \
    "    TargetName         Type       Endian TapName            State" \
    "targets command header"
  send "reset halt ; targets \n"
  expectExpr $spawn_id \
    "    TargetName         Type       Endian TapName            State" \
    "targets command header"

  set NUM_CORES [target_info cpu,cores_num]
  for { set CoreIndex 0 } { $CoreIndex < $NUM_CORES } { incr CoreIndex } {
    expectExpr $spawn_id "halted\r\n" "target state"
  }
  expectExpr $spawn_id "\r\n" "target newlines"
  send "help\n"
  expectExpr $spawn_id "\r\n\r>" "prompt after help"
  send "shutdown\n"
  expectExpr $spawn_id "OpenOCD exit code indicates SUCCESS" "final message"
  expect {
    eof {
    }
    timeout {
      close
      wait
      error "unexpected timeout while waiting for shutdown"
    }
  }
}

proc expectScriptCleanup { spawn_id } {
  set ScriptResults [wait]
  verbose "script result: $ScriptResults"
  set Status [lindex $ScriptResults 3]
  if { $Status != 0 } {
    error "script reports failure (unexpected)"
  }
}

proc run_test {} {
  set script_to_run "[ocdtlb_test_resource_path run_script_targets.tcl]"

  set TelnetLog [utils_spawn_universal_launcher \
    [list --run-script $script_to_run --telnet] \
    telnet  \
    interactive]
  expectTelnetStartup $spawn_id
  expectTelnetTargetListing $spawn_id
  expectScriptCleanup $spawn_id

  # NOTE: the output of the script is part of the primary spawn log, since
  # scripts specified as an argument to `--run-script` are processed before
  # TCL-server is created
  set NUM_CORES [target_info cpu,cores_num]
  exec grep --text -F "==== RUN_SCRIPT_TEST ==== Number of Targets: $NUM_CORES" $TelnetLog
  return [ocd_test_pass]
}

return [run_test]
