proc run_test {} {
  set log_path [utils_spawn_universal_launcher \
    [list --help]  help  expect_success]

  set options [list \
    auto-config \
    bindto \
    bitbang-port \
    configure-hook \
    debug-adapter-index \
    debug-adapter-serial \
    disable-ebreak \
    disable-interactive-mode \
    help \
    ide-mode \
    i-know-what-im-doing \
    jtag-topology \
    log-session \
    no-extra-scripts \
    no-targets \
    reset-adapter \
    run-command \
    run-script \
    scan-only \
    single-core \
    smp \
    speed \
    spike-arg \
    spike-bin \
    spike-harts \
    stand-db \
    telnet \
    verbose \
  ]
  foreach option $options {
    exec grep --text -F -- "--$option" $log_path
  }

  return [ocd_test_pass]
}

return [run_test]
