proc run_test {} {
    set default_bin_prefix [tool_state_get default_bin_prefix]
    ocd_compile_executable "lib/memory.S" "$default_bin_prefix.exe"

    set ENTRY_ADDR [tool_state_get_program_symbol _entry]
    set true_data 0xdeadbeef

    set script_path [get_sc_lowlevel_jtag_lib_path]
    set commands_path [ocdtlb_test_resource_path memory_access_special_commands.tcl]
    set runner_path [ocdtlb_test_resource_path command_runner.tcl]

    set LogFile [utils_spawn_universal_launcher \
        [list \
            --no-targets \
            --run-script $script_path \
            --run-command "set ENTRY_ADDR $ENTRY_ADDR" \
            --run-command "set true_data $true_data" \
            --run-script $commands_path \
            --run-script $runner_path \
            --run-command shutdown] \
        memory_access_special \
        expect_success]

    if {![catch {exec grep --text -F "ERROR:" $LogFile} error_str]} {
        error $error_str
    }

    set load_result [exec grep --text -F "load_memory result:" -n $LogFile]
    set load_result_str_list [split $load_result "\n"]
    set load_result_str [lindex $load_result_str_list 2]

    if {![regexp "0x\[0-9a-f\]+" $load_result_str load_result]} {
        error "incorrect output of load_memory"
    } elseif { $true_data != $load_result } {
        error "incorrect output of load_memory: $load_result; should be $true_data"
    }

    return [ocd_test_pass]
}

return [run_test]