default:
  tags:
    - ci
  interruptible: true

variables:
  GIT_STRATEGY: clone
  ARTIFACTORY_API_KEY: $CICD_TOOLS_SC_ARTIFACTORY_API_KEY
  BUILD_ID: gitlab_job_$CI_JOB_ID
  BUILD_TYPE: Release
  COMMON_BUILD_DIR: /home/ci_user/build

main-job:
  script:
    - sudo chown -R ci_user .
    - make container -f .ci/makefile
    - make in_docker TARGET=build -f .ci/makefile
    - exit_code=0
    - make in_docker TARGET=test -f .ci/makefile || exit_code=$?
    - |
      if [[ "$exit_code" -ne 0 ]]; then
        make in_docker TARGET=upload_test_report -f .ci/makefile
        exit $exit_code
      fi
    - make in_docker TARGET=riscv-tests-debug -f .ci/makefile
    - make in_docker TARGET=package -f .ci/makefile
    - ./.ci/utils/upload_development_build.sh
        $COMMON_BUILD_DIR/linux/install_openocd/linux_openocd.tar.gz
    - ./.ci/utils/upload_development_build.sh
        $COMMON_BUILD_DIR/windows/install_openocd/windows_openocd.zip
    - |
      if [[ "$UPLOAD_STABLE_BUILDS" == "true" ]]; then
        ./.ci/utils/check_nightly_status.sh "$ARTIFACTORY_API_KEY" || exit_code=$?
        if [[ "$exit_code" -eq 0 ]]; then
          # Upload release artifacts
          ./.ci/utils/upload_artifact.sh $COMMON_BUILD_DIR/linux/install_openocd/linux_openocd.tar.gz
          ./.ci/utils/upload_artifact.sh $COMMON_BUILD_DIR/linux/install_openocd/windows_openocd.zip
        else
          echo "could not find recods indicating that nightly passed"
          echo "no artifacts for stable builds produced"
        fi
      fi
