[project]
name = "openocd"
version = "0.0.0"
requires-python = ">=3.10"

[dependency-groups]
dev = [
  "black>=24.1.1",
  "cmakelang>=0.6.13",
  "hwrs>=0.2.0",
  "isort>=5.13.2",
  "lgrw>=0.3.10",
  "makepy>=1.2504a20",
  "mypy>=1.8.0",
  "pexpect>=4.9.0",
  "pylint>=3.0.3",
  "requests>=2.31.0",
  "yamllint>=1.33.0",
  "labgrid>=23.1a3.dev58",
]

[tool.makepy]
legacy_venv = false

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80

[tool.mypy]
strict = true
disable_error_code = [
  "import-untyped",
  "attr-defined"
]

[tool.pylint]
max-line-length = 80
disable = [
  "empty-docstring",
  "fixme",
  "logging-fstring-interpolation",
  "logging-not-lazy",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-branches",
  "too-many-instance-attributes",
  "too-many-locals",
  "too-many-statements",
  "line-too-long"
]
