set TGT_ARCH "rv32gc"

add_board_info cpu,xlen 32
set_board_info cpu,has_floats 1
set_board_info cpu,has_doubles 1
set_board_info cpu,has_u_mode 1
set_board_info cpu,has_s_mode 0
set_board_info cpu,has_h_ext 0

set_board_info cpu,has_v_ext 0
set_board_info cpu,v_ext_vlen 0
set_board_info cpu,v_ext_elen 0

set_board_info cpu,has_watchpoints 1
set_board_info cpu,has_watchpoints_equal 1
set_board_info cpu,has_watchpoints_napot 1
set_board_info cpu,has_watchpoints_gelt 1
set_board_info cpu,has_watchpoints_data_mask 0

set_board_info cpu,sv32 0
set_board_info cpu,sv39 0
set_board_info cpu,sv48 0
set_board_info cpu,sv57 0

set_board_info cpu,sv32x4 0
set_board_info cpu,sv39x4 0
set_board_info cpu,sv48x4 0
set_board_info cpu,sv57x4 0

set_board_info cpu,misaligned_access_support 0

set_board_info cpu,dm_abstract_csr 1
set_board_info cpu,dm_abstract_fpr 1

add_board_info cflags   -march=$TGT_ARCH
add_board_info cflags   -mabi=ilp32d
