set_board_info cpu,xlen 32
set_board_info cpu,has_floats 1
set_board_info cpu,has_doubles 1
set_board_info cpu,has_u_mode 1
set_board_info cpu,has_s_mode 1
set_board_info cpu,has_h_ext 1

set_board_info cpu,has_pmp 1
set_board_info cpu,has_pmp_napot 1
set_board_info cpu,has_pmp_top 1

set_board_info cpu,has_v_ext 0
set_board_info cpu,v_ext_vlen 0
set_board_info cpu,v_ext_elen 0
set_board_info cpu,v_ext_misa_writable 0

set_board_info cpu,trigger_count 4

set_board_info cpu,has_hw_breakpoints 1
set_board_info cpu,hwbp_hit_bit_support 1

set_board_info cpu,has_watchpoints 1
set_board_info cpu,has_watchpoints_equal 1
set_board_info cpu,has_watchpoints_napot 1
set_board_info cpu,has_watchpoints_gelt 1
set_board_info cpu,has_watchpoints_data_mask 0
set_board_info cpu,wp_eq_matches_on_crossing 0
set_board_info cpu,wp_napot_matches_on_crossing 0
set_board_info cpu,wp_gelt_matches_on_crossing 0
set_board_info cpu,wp_hit_bit_support 1

set_board_info cpu,has_icount 1

set_board_info cpu,mtvec_balign 4
set_board_info cpu,stvec_balign 4

set_board_info cpu,sv32 1
set_board_info cpu,sv39 0
set_board_info cpu,sv48 0
set_board_info cpu,sv57 0

set_board_info cpu,sv32x4 1
set_board_info cpu,sv39x4 0
set_board_info cpu,sv48x4 0
set_board_info cpu,sv57x4 0

set_board_info cpu,misaligned_access_support 0

set_board_info cpu,dm_run_read_pc 0

set_board_info cpu,dm_abstract_csr 0
set_board_info cpu,dm_abstract_fpr 0
set_board_info cpu,dm_is_slow 0

set_board_info cpu,dm_sba_access_enable 0
set_board_info cpu,dcsr_ebreakx_warl 1

add_board_info cflags   -march=rv32gc
add_board_info cflags   -mabi=ilp32d

add_board_info sim,options --dm-progsize=6
add_board_info sim,options --dm-sba=0
add_board_info sim,options --dm-abstract-rti=0

add_board_info sim,options --dm-no-abstract-csr
add_board_info sim,options --dm-no-abstract-fpr

set_board_info sim,ext_isa_info {}
