set TGT_ARCH "rv64gcv"

set_board_info cpu,xlen 64
set_board_info cpu,has_floats 1
set_board_info cpu,has_doubles 1
set_board_info cpu,has_u_mode 1
set_board_info cpu,has_s_mode 1
set_board_info cpu,has_h_ext 1

set_board_info cpu,has_v_ext 1
set_board_info cpu,v_ext_vlen 128
set_board_info cpu,v_ext_elen 64

set_board_info cpu,misaligned_access_support 0

set_board_info cpu,dm_abstract_csr 1
set_board_info cpu,dm_abstract_fpr 1

add_board_info cflags   -march=$TGT_ARCH
add_board_info cflags   -mabi=lp64d

add_board_info sim,options --isa=$TGT_ARCH
add_board_info sim,options --dm-progsize=6
add_board_info sim,options --dm-sba=0
add_board_info sim,options --dm-abstract-rti=100
add_board_info sim,options --dmi-rti=100
