set TGT_ARCH "rv32gc"

set_board_info cpu,xlen 32
set_board_info cpu,cores_num 1
set_board_info cpu,has_floats 1
set_board_info cpu,has_doubles 1
set_board_info cpu,has_u_mode 1
set_board_info cpu,has_s_mode 1
set_board_info cpu,has_h_ext 1

set_board_info cpu,has_v_ext 0

set_board_info cpu,dm_abstract_csr 1
set_board_info cpu,dm_abstract_fpr 1

add_board_info cflags   -march=$TGT_ARCH
add_board_info cflags   -mabi=ilp32d

add_board_info sim,options --isa=$TGT_ARCH
add_board_info sim,options --dm-progsize=6
add_board_info sim,options --dm-sba=32
add_board_info sim,options --dm-abstract-rti=0
