if {![target_info cpu,has_floats]} { return [ocd_test_unsupported] }

proc run_test {} {
  global FPR

  set xlen64 [expr [target_info cpu,xlen] == 64]

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "fpr_rw_basic.S" "$default_bin_prefix.exe"

  # created by compile executable
  set ENTRY_ADDR [tool_state_get_program_symbol _entry]
  set END_ADDR [tool_state_get_program_symbol end]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"
  set STEP_LIMIT 100
  ocdtlb_do_expect_step_until $END_ADDR $STEP_LIMIT

  set prev 1
  set values(0) 0
  for {set i 1} {$i < 32} {incr i} {
    if {$xlen64} {
      set values($i) [expr ($prev | (1 << (2 * $i)))]
    } else {
      set values($i) [expr ($prev | (1 << $i))]
    }

    set prev $values($i)
  }

  for {set i 0} {$i < 32} {incr i} {
    ocdtlb_run_expect "reg $FPR($i) $values($i)"
  }

  ocdtlb_run_expect "step"

  for {set i 0} {$i < 32} {incr i} {
    set value [ocdtlb_rsp_get [ocdtlb_run_expect "reg $FPR($i)"]]
    ocdtlb_expect_equal $values($i) $value
  }

  ocdtlb_run_expect "reg fcsr 0xff"
  set fcsr [ocdtlb_rsp_get [ocdtlb_run_expect "reg fcsr"]]
  set fflags [ocdtlb_rsp_get [ocdtlb_run_expect "reg fflags"]]
  ocdtlb_expect_equal $fflags 0x1f
  set frm [ocdtlb_rsp_get [ocdtlb_run_expect "reg frm"]]
  ocdtlb_expect_equal $frm 0x7

  ocdtlb_run_expect "reg fflags 0x0"
  set fcsr [ocdtlb_rsp_get [ocdtlb_run_expect "reg fcsr"]]
  ocdtlb_expect_equal $fcsr 0xe0

  ocdtlb_run_expect "reg frm 0x0"
  set fcsr [ocdtlb_rsp_get [ocdtlb_run_expect "reg fcsr"]]
  ocdtlb_expect_equal $fcsr 0x0

  return [ocd_test_pass]
}

return [run_test]
