proc run_test {} {

  global default_bin_prefix
  global program_info
  global GPR

  set xlen64 [expr [target_info cpu,xlen] == 64]

  ocd_compile_executable "basic.S" "$default_bin_prefix.exe"

  # created by compile executable
  set ENTRY_ADDR $program_info(_entry)
  set END_ADDR $program_info(end)

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "load_image $default_bin_prefix.exe"
  ocdtlb_run_expect "reg pc $ENTRY_ADDR"
  ocdtlb_run_expect "bp $END_ADDR 4"
  ocdtlb_run_expect "resume"

  octdlb_wait_resume

  ocdtlb_do_expect_halted

  for {set i 1} {$i < 32} {incr i} {

    set reg_name $GPR($i)
    set value [ocdtlb_rsp_get [ocdtlb_run_expect "reg $reg_name"]]

    if {$xlen64} {
      set expected [expr 2 << (($i - 1) * 2)]
    } else {
      set expected [expr 1 << ($i - 1)]
    }

    verbose "$reg_name / $value \\/ $expected" 1
    ocdtlb_expect_equal $expected $value
  }
  set reg0 [ocdtlb_rsp_get [ocdtlb_run_expect "reg $GPR(0)"]]
  ocdtlb_expect_equal 0 $reg0

  return [ocd_test_pass]
}

return [run_test]
