proc run_test {} {
  set xlen64 [expr [target_info cpu,xlen] == 64]

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "halt_reason.S" "$default_bin_prefix.exe"

  # created by compile executable
  set ENTRY_ADDR [tool_state_get_program_symbol _entry]
  set MAIN_ADDR [tool_state_get_program_symbol main]
  set LOAD_INSTR_ADDR [tool_state_get_program_symbol load_instr]
  set SIMPLE_INSTR_ADDR [tool_state_get_program_symbol simple_instr]
  set LOAD_ADDR [tool_state_get_program_symbol work_area_start]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "load_image $default_bin_prefix.exe"
  ocdtlb_run_expect "resume $ENTRY_ADDR"
  ocdtlb_run_expect "halt"

  set AfterHalt [ocdtlb_target_command current debug_reason]
  ocdtlb_expect_equal "debug-request" $AfterHalt

  ocdtlb_run_expect "step"
  set AfterStep [ocdtlb_target_command current debug_reason]
  ocdtlb_expect_equal "single-step" $AfterStep

  set ResumeCapture [ocdtlb_run_catch_and_capture "resume"]
  if {[string first halt $ResumeCapture] != -1} {
    error "unexpected output of *resume* command detected: $ResumeCapture"
  }

  ocdtlb_run_expect "halt"
  ocdtlb_run_expect "bp $MAIN_ADDR 4"
  ocdtlb_run_expect "resume $ENTRY_ADDR"
  ocdtlb_wait_resume wait_halt
  set AfterSwBp [ocdtlb_target_command current debug_reason]
  ocdtlb_expect_equal "breakpoint" $AfterSwBp
  ocdtlb_run_expect "rbp $MAIN_ADDR"

  # Here we test a situation when only HW breakpoint is set
  if {[target_info cpu,has_hw_breakpoints]} {
    ocdtlb_run_expect "bp $SIMPLE_INSTR_ADDR 4 hw"
    ocdtlb_run_expect "resume $ENTRY_ADDR"
    ocdtlb_wait_resume wait_halt
    set OnBpHalt_Single [ocdtlb_target_command current debug_reason]

    ocdtlb_expect_equal "breakpoint" $OnBpHalt_Single
    ocdtlb_run_expect "rbp $SIMPLE_INSTR_ADDR"
  }

  if {[target_info cpu,has_watchpoints]} {
    # Here we test a situation when only Watchpoint is set
    ocdtlb_run_expect "wp $LOAD_ADDR 4"
    ocdtlb_run_expect "resume $ENTRY_ADDR"
    ocdtlb_wait_resume wait_halt
    set OnWpHalt_Single [ocdtlb_target_command current debug_reason]

    ocdtlb_expect_equal "watchpoint" $OnWpHalt_Single
    ocdtlb_run_expect "rwp $LOAD_ADDR"
  }

  if {[target_info cpu,has_hw_breakpoints] && [target_info cpu,has_watchpoints]} {
    # Here we test a situation when both HW breakpoints and Watchpoints are set
    ocdtlb_run_expect "wp $LOAD_ADDR 4"
    ocdtlb_run_expect "bp $SIMPLE_INSTR_ADDR 4 hw"

    ocdtlb_run_expect "resume $ENTRY_ADDR"
    ocdtlb_wait_resume wait_halt
    set OnWpHalt [ocdtlb_target_command current debug_reason]

    ocdtlb_run_expect "resume"
    ocdtlb_wait_resume wait_halt
    set OnBpHalt [ocdtlb_target_command current debug_reason]

    ocdtlb_run_expect "resume"
    ocdtlb_wait_resume wait_halt
    set OnWpAgain [ocdtlb_target_command current debug_reason]

    ocdtlb_expect_equal "watchpoint" $OnWpHalt
    ocdtlb_expect_equal "watchpoint" $OnWpAgain
    ocdtlb_expect_equal "breakpoint" $OnBpHalt
  }
  return [ocd_test_pass]
}

return [run_test]
