set xlen64 [expr [target_info cpu,xlen] == 64]

ocd_compile_executable "basic.S" "$default_bin_prefix.exe"

# created by compile executable
set MEM_ADDR $program_info(work_area_start)

ocd_connect

ocdtlb_run_expect "targets 0"
ocdtlb_run_expect "reset halt"

ocdtlb_run_expect "load_image $default_bin_prefix.exe"

set supported_widths { 8 16 32}
# It seems that 64-bit read mem does not work correctly
#if {$xlen64} {
#  lappend supported_widths 64
#}

set expected_data1(8)  {0xad}
set expected_data1(16) {0xddad}
set expected_data1(32) {0xbaddad}

set expected_data2(8)  {0xad 0xdd}
set expected_data2(16) {0xddad 0xba}
set expected_data2(32) {0xbaddad 0xdeadbabe}

foreach width $supported_widths {
  set response [ocdtlb_run_expect "read_memory $MEM_ADDR $width 1"]
  set data [ocdtlb_rsp_get $response data]
  ocdtlb_expect_equal_hex $data $expected_data1($width)
}

foreach width $supported_widths {
  set response [ocdtlb_run_expect "read_memory $MEM_ADDR $width 2"]
  set data [ocdtlb_rsp_get $response data]
  ocdtlb_expect_equal_hex $data $expected_data2($width)
}

ocd_test_pass
