proc run_test {} {
  set xlen64 [expr [target_info cpu,xlen] == 64]

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "basic.S" "$default_bin_prefix.exe"

  # created by compile executable
  set MEM_ADDR [tool_state_get_program_symbol mdd_test_data]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "load_image $default_bin_prefix.exe"

  set response [ocdtlb_run_expect "mdb $MEM_ADDR"]
  set bytes [dict get $response data]
  ocdtlb_expect_equal $bytes [list 0xad]

  set response [ocdtlb_run_expect "mdh $MEM_ADDR"]
  set bytes [dict get $response data]
  ocdtlb_expect_equal $bytes [list 0xddad]

  set response [ocdtlb_run_expect "mdw $MEM_ADDR"]
  set bytes [dict get $response data]
  ocdtlb_expect_equal $bytes [list 0x00baddad]

  if {$xlen64} {
    set response [ocdtlb_run_expect "mdd $MEM_ADDR"]
    set bytes [dict get $response data]
    ocdtlb_expect_equal $bytes [list 0xdeadbabe00baddad]
  }

  return [ocd_test_pass]
}

return [run_test]
