if {![ocd_check_platform_requirements]} { return [ocd_test_unsupported] }

ocd_connect

proc check_reg_availability {reg_name tgt_reg_list check_type} {
  set EXPECT_FAILURE 1
  set EXPECT_SUCCESS 0
  verbose "testing for <$reg_name> - $check_type" 1
  switch -exact $check_type {
    MUST_BE_AVAILABLE {
      if {[lsearch -exact $tgt_reg_list $reg_name] >= 0} {
        verbose "$reg_name is found in tgt_reg_list - OK"
      } else {
        error "$reg_name is NOT found in tgt_reg_list"
      }
      ocdtlb_run_expect "reg $reg_name" $EXPECT_SUCCESS
    }
    MUST_BE_ABSENT {
      if {[lsearch -exact $tgt_reg_list $reg_name] >= 0} {
        error "$reg_name is unexpectedly found in tgt_reg_list"
      } else {
        verbose "$reg_name is NOT found in tgt_reg_list - OK"
      }
      ocdtlb_run_expect "reg $reg_name" $EXPECT_FAILURE
    }
    default {
      error "unexpected check type"
    }
  }
}

ocdtlb_run_expect "reset halt"

set rs [ocdtlb_run_expect "reg"]

set found_registers [ocdtlb_rsp_get $rs found_name]


if {[expr { [target_info cpu,has_u_mode] || [target_info cpu,has_s_mode] }] } {
  check_reg_availability mcounteren $found_registers MUST_BE_AVAILABLE
} else {
  check_reg_availability mcounteren $found_registers MUST_BE_ABSENT
}

return [ocd_test_pass]


