if {![ocd_check_platform_requirements]} { return [ocd_test_unsupported] }

ocd_connect

proc check_reg_availability {reg_name tgt_reg_list check_type} {
  set EXPECT_FAILURE 1
  set EXPECT_SUCCESS 0
  verbose "testing for <$reg_name> - $check_type" 1
  switch -exact $check_type {
    MUST_BE_AVAILABLE {
      ocdtlb_expect_present $tgt_reg_list $reg_name
      ocdtlb_run_expect "reg $reg_name" $EXPECT_SUCCESS
    }
    MUST_BE_ABSENT {
      ocdtlb_expect_missing $tgt_reg_list $reg_name
      ocdtlb_run_expect "reg $reg_name" $EXPECT_FAILURE
    }
    default {
      error "unexpected check type"
    }
  }
}

set ALWAYS_AVAILABLE_REGS [list \
    cycle \
    instret \
    marchid \
    mcause \
    mcycle \
    mepc \
    mhartid \
    mie \
    mimpid \
    minstret \
    mip \
    misa \
    mscratch \
    mstatus \
    mtval \
    mtvec \
    mvendorid \
    time \
]

set ALWAYS_MISSING_REGS {}
for {set i 3} {$i < 32} {incr i} {
  lappend ALWAYS_MISSING_REGS HPMCOUNTER${i}H
  lappend ALWAYS_MISSING_REGS MHPMCOUNTER${i}H
}

ocdtlb_run_expect "reset halt"

set rs [ocdtlb_run_expect "reg"]

set found_registers [ocdtlb_rsp_get $rs found_name]


if {[expr { [target_info cpu,has_u_mode] || [target_info cpu,has_s_mode] }] } {
  check_reg_availability mcounteren $found_registers MUST_BE_AVAILABLE
} else {
  check_reg_availability mcounteren $found_registers MUST_BE_ABSENT
}

foreach available_reg $ALWAYS_AVAILABLE_REGS {
  check_reg_availability $available_reg $found_registers MUST_BE_AVAILABLE
}

foreach available_reg $ALWAYS_MISSING_REGS {
  check_reg_availability $available_reg $found_registers MUST_BE_ABSENT
}

return [ocd_test_pass]


