proc run_test {} {
  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "basic.S" "$default_bin_prefix.exe"

  # created by compile executable
  set ENTRY_ADDR [tool_state_get_program_symbol _entry]
  set END_ADDR [tool_state_get_program_symbol end]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "load_image $default_bin_prefix.exe"
  ocdtlb_run_expect "reg pc $ENTRY_ADDR"

  set STEP_LIMIT 100

  for { set count 0 } { $count < $STEP_LIMIT } { incr count } {

    ocdtlb_run_expect "step"
    set response [ocdtlb_run_expect "reg pc"]
    set cur_pc   [ocdtlb_rsp_get $response]

    if { [ocdtlb_compare_equal_hex $cur_pc $END_ADDR]} {
      return [ocd_test_pass]
    }
  }

  error "could not reach $END_ADDR, tried $count steps"
}

return [run_test]

