proc run_test {} {
  global GPR

  set xlen64 [expr [target_info cpu,xlen] == 64]

  set default_bin_prefix [tool_state_get default_bin_prefix]
  # created by compile executable
  ocd_compile_executable "step_at.S" "$default_bin_prefix.exe"

  set ENTRY_ADDR [tool_state_get_program_symbol _entry]
  set END_ADDR [tool_state_get_program_symbol end]
  set INSTR1_ADDR [tool_state_get_program_symbol instr1]
  set INSTR2_ADDR [tool_state_get_program_symbol instr2]
  set INSTR3_ADDR [tool_state_get_program_symbol instr3]
  set AFTER3_ADDR [tool_state_get_program_symbol after3]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "load_image $default_bin_prefix.exe"
  ocdtlb_run_expect "reg pc $ENTRY_ADDR"
  ocdtlb_run_expect "bp $END_ADDR 4"
  ocdtlb_run_expect "resume"

  octdlb_wait_resume

  ocdtlb_do_expect_halted

  ocdtlb_run_expect "step $INSTR1_ADDR"
  set reg1 [ocdtlb_rsp_get [ocdtlb_run_expect "reg $GPR(1)"]]

  ocdtlb_run_expect "step $INSTR2_ADDR"
  set reg2 [ocdtlb_rsp_get [ocdtlb_run_expect "reg $GPR(2)"]]

  ocdtlb_run_expect "step $INSTR3_ADDR"
  set reg3 [ocdtlb_rsp_get [ocdtlb_run_expect "reg $GPR(3)"]]

  set pca3 [ocdtlb_rsp_get [ocdtlb_run_expect "reg pc"]]

  ocdtlb_expect_equal_hex   $reg1 0x00000000000002c4

  if {$xlen64} {
    ocdtlb_expect_equal_hex $reg2 0xfffffffffffffd90
  } else {
    ocdtlb_expect_equal_hex $reg2 0xfffffd90
  }

  ocdtlb_expect_equal_hex   $reg3 0x00000000000005a3
  ocdtlb_expect_equal_hex   $pca3 $AFTER3_ADDR

  return [ocd_test_pass]
}

return [run_test]

