load_lib "lib_elf_ripper.exp"
load_lib "lib_abi_compat.exp"
load_lib "lib_response.exp"
load_lib "lib_test.exp"
load_lib "lib_tool_support.exp"
load_lib "lib_tool_state.exp"
load_lib "lib_lowlevel_jtag.exp"

proc jtag_init {test_file_name} {
  global OCD_PORT_TCLRPC
  global ENABLE_EXP_INTERNAL
  global timeout

  exp_internal $ENABLE_EXP_INTERNAL
  match_max -d 1000000
  set timeout [target_info env,preferred_timeout]
  verbose "/// ocd_jtag_init \\\\\\" 1

  tsuplib_ensure_target_properties [list \
    openocd,jtag_tool_tap_definition_flags
  ]
  tsuplib_launch_openocd jtag \
                         $test_file_name \
                         [standInfoGetInterfaceFlags] \
                         [target_info openocd,jtag_tool_tap_definition_flags]

  if {[catch { \
        tsuplib_wait_for_openocd_initialization [tool_state_get openocd_log] \
                                                 $OCD_PORT_TCLRPC \
                                                 none} \
      ERR_INFO]} {
    perror "$ERR_INFO"
    puts "looks like OpenOCD does not respond. Sending kill signal"
    set spawn_id [tool_state_steal openocd_spawn_id]
    exec kill -s SIGKILL [exp_pid -i $spawn_id ]
    close
    wait -nowait
    verbose "\\\\\\ ocd_jtag_init (FAILED) ///\n   _______" 1
    return
  }

  tool_state_update openocd_tclrpc_port $OCD_PORT_TCLRPC

  verbose "\\\\\\ ocd_jtag_init ///\n   _______" 1
}

proc jtag_finish {{ cleanup_type "immediate" }} {
  verbose "/// ocd_jtag_finish \\\\\\" 1

  tsuplib_disconnect_client
  tsuplib_shutdown_openocd $cleanup_type

  verbose "\\\\\\ ocd_jtag_finish ///\n   _______" 1
}

proc jtag_connect { {need_scan_and_restart 1} } {
  tsuplib_tclrcp_connect

  if {$need_scan_and_restart == 1} {
    global taps_info

    ocdjtag_riscv_update_taps_info

    if {[dict get $taps_info count] == 0} {
        perror "No harts found"
        return [ocd_test_fail]
    }

    set count [dict get $taps_info count]

    for {set i 0} {$i < $count} {incr i} {
        ocdjtag_riscv_reset_dm $i
    }
  }
}

