set ARF_names [dict create \
  x0  zero \
  x1  ra \
  x2  sp \
  x3  gp \
  x4  tp \
  x5  t0 \
  x6  t1 \
  x7  t2 \
  x8  fp \
  x9  s1 \
  x10 a0 \
  x11 a1 \
  x12 a2 \
  x13 a3 \
  x14 a4 \
  x15 a5 \
  x16 a6 \
  x17 a7 \
  x18 s2 \
  x19 s3 \
  x20 s4 \
  x21 s5 \
  x22 s6 \
  x23 s7 \
  x24 s8 \
  x25 s9 \
  x26 s10 \
  x27 s11 \
  x28 t3 \
  x29 t4 \
  x30 t5 \
  x31 t6 \
  f0  ft0  \
  f1  ft1  \
  f2  ft2  \
  f3  ft3  \
  f4  ft4  \
  f5  ft5  \
  f6  ft6  \
  f7  ft7  \
  f8  fs0  \
  f9  fs1  \
  f10 fa0  \
  f11 fa1  \
  f12 fa2  \
  f13 fa3  \
  f14 fa4  \
  f15 fa5  \
  f16 fa6  \
  f17 fa7  \
  f18 fs2  \
  f19 fs3  \
  f20 fs4  \
  f21 fs5  \
  f22 fs6  \
  f23 fs7  \
  f24 fs8  \
  f25 fs9  \
  f26 fs10 \
  f27 fs11 \
  f28 ft8  \
  f29 ft9  \
  f30 ft10 \
  f31 ft11 \
]

proc build_canonical_map {} {
  global ARF_names
  dict for {canonical_name abi_name} $ARF_names {
    global $canonical_name
    set $canonical_name $canonical_name
  }
}

proc build_abi_map {} {
  global ARF_names
  dict for {canonical_name abi_name} $ARF_names {
    global $abi_name
    set $abi_name $abi_name
  }
}

# compatibility layer for openocd version > 0.10
proc build_forward_compat {} {
  global ARF_names
  dict for {canonical_name abi_name} $ARF_names {
    global $canonical_name
    set $canonical_name $abi_name
  }
  global GPR
  global FPR
  for {set i 0} {$i < 32} {incr i} {
    set GPR($i) [subst "\$x$i"]
    set FPR($i) [subst "\$f$i"]
  }
}

# compatiblity layer for openocd version <= 0.10
proc build_backward_compat {} {
  global ARF_names
  dict for {canonical_name abi_name} $ARF_names {
    global $abi_name
    set $abi_name $canonical_name
  }
  global GPR
  global FPR
  for {set i 0} {$i < 32} {incr i} {
    set gpr_abi_name [dict get $ARF_names "x$i"]
    set fpr_abi_name [dict get $ARF_names "f$i"]
    set GPR($i) [subst "\$$gpr_abi_name"]
    set FPR($i) [subst "\$$fpr_abi_name"]
  }
}

build_canonical_map
build_abi_map
