load_lib "lib_abi_compat.exp"

proc ocd_scaled_delay_value { per_core_delay } {
  set cores_num [target_info cpu,cores_num]
  return [expr { $cores_num * $per_core_delay} ]
}

proc ocd_resume_delay {} {
  return [ocd_scaled_delay_value [target_info env,resume_delay]]
}

proc ocd_exec_delay {} {
  return [ocd_scaled_delay_value [target_info env,exec_delay]]
}

proc tsuplib_ensure_target_properties { property_list } {
  set error_detected 0
  foreach property $property_list {
    if {[target_info $property] == ""} {
      perror "target definition does not have $property set"
      set error_detected 1
    }
  }

  if {$error_detected} {
    set target_name [target_info name]
    perror "currently selected target <$target_name> is not configured properly, aborting"
    # FIXME: probably, exit 1 is too harsh
    exit 1
  }
}

proc tsuplib_target_info_check {} {
  return [tsuplib_ensure_target_properties [list \
    cpu,xlen \
    cpu,name \
    cpu,cores_num \
    cpu,has_floats \
    cpu,has_doubles \
    cpu,has_u_mode \
    cpu,has_s_mode \
    cpu,has_h_ext \
    cpu,has_v_ext \
    cpu,misaligned_access_support \
    cpu,dm_abstract_csr \
    cpu,dm_abstract_fpr \
    memory,reset_vector \
    memory,has_high_pa \
    memory,ocd_work_area \
    openocd,hwthreads \
    openocd,extra_csr \
    openocd,smp_target \
    openocd,abi_regnames \
    openocd,hidden_triggers \
    openocd,ide_cloak \
    env,preferred_timeout \
    env,resume_delay \
    env,exec_delay \
  ]]
}

proc tsuplib_determine_openocd_version {} {
  global OPENOCD
  set OPENOCD_VARIANT "unknown"
  spawn $OPENOCD "--version"
  expect {
    -re "Open On-Chip Debugger \[0-9.\]+" {
      if {[regexp "Open On-Chip Debugger 0.10.0" $expect_out(buffer)]} {
        set OPENOCD_VARIANT "legacy"
      } elseif {[regexp "Open On-Chip Debugger 0.11.0" $expect_out(buffer)]} {
        set OPENOCD_VARIANT "latest"
      } elseif {[regexp "Open On-Chip Debugger 0.12.0" $expect_out(buffer)]} {
        set OPENOCD_VARIANT "bleeding_edge"
      }
      verbose "reported OpenOCD version: $expect_out(buffer)" 2
    }
    eof {
      error "could not identify openocd variant (unexpected EOF)"
    }
    timeout {
      perror "could not identify openocd variant (unexpected TIMEOUT)"
    }
  }
  # clean up resources from the version invocation
  close
  wait -nowait

  return $OPENOCD_VARIANT
}

proc tsuplib_wait_for_file { filename max_retries poll_delay } {
  for {set retries_count 0} {![file exists $filename]} {incr retries_count} {
    verbose "waiting for the $filename to materialize... attempt #$retries_count" 2

    if {$retries_count > $max_retries} {
      error "failed to wait for $filename"
    }

    sleep $poll_delay
  }
  verbose "$filename detected" 1
}

proc tsuplib_wait_for_acknowledge { tcl_log primary_pattern max_retry_count poll_delay } {
  set ack_detected 0
  for { set it_count 0 } { $it_count < $max_retry_count } { incr it_count } {
    set listen_pattern "Listening on\\|error"
    spawn grep -i $listen_pattern $tcl_log
    expect {
      -re "LIBUSB_ERROR_BUSY" {
        close
        wait -nowait
        error "LIBUSB_ERROR_BUSY encountered while waiting for ($primary_pattern)"
      }
      -re "EXAMINATION FAILURE\n" {
        close
        wait -nowait
        error "target examination failed unexpectedly"
      }
      -re "Timed out after" {
        close
        wait -nowait
        error "target examination (?) resulted in timeout"
      }
      -re "$primary_pattern" {
        verbose "ack_detected! ($primary_pattern)" 1
        set ack_detected 1
      }
      eof {
        verbose "EOF while waiting for ($primary_pattern), attempt #$it_count" 3
        wait -nowait
        sleep $poll_delay
        continue
      }
      timeout  {
        verbose "could not scan log while waiting for ($primary_pattern), attempt #$it_count" 3
      }
    }
    close
    wait -nowait

    if { $ack_detected } {
      return
    }
  }
  error "could not get initial ack while waiting for $primary_pattern (it num: $it_count)"
}

proc tsuplib_launch_openocd { tool_name \
                              test_file_name \
                              interface_flags \
                              target_flags} {
  global OPENOCD
  global OPENOCD_LOG_LEVEL

  tool_ensure_pristine_state
  tsuplib_target_info_check

  if {[catch { tsuplib_determine_openocd_version } openocd_variant]} {
    perror $openocd_variant
    return
  }

  verbose "selected OpenOCD variant: $openocd_variant" 1

  if {[string equal $openocd_variant "latest"]} {
    if {[target_info openocd,abi_regnames] == 0} {
      build_forward_compat
    } else {
      build_backward_compat
    }
  } elseif {[string equal $openocd_variant "legacy"]} {
    build_backward_compat
  } else {
    perror "unexpected OpenOCD version $openocd_variant"
    return
  }

  set ocd_test_name [file rootname [file tail $test_file_name]]
  tool_state_update test_name $ocd_test_name

  # format is #{tool_name}_${board_name}_${test_name}
  set test_identifier "${tool_name}_[target_info name]_${ocd_test_name}"
  tool_state_update default_bin_prefix $test_identifier

  set ocd_test_log "${test_identifier}.log"
  tool_state_update openocd_log $ocd_test_log

  if {[catch {exec rm ${ocd_test_log}} result]} {
    verbose "ignore this: $result" 2
  } else {
    verbose "${ocd_test_log} removed" 1
  }

  set openocd_args [concat \
    "-d$OPENOCD_LOG_LEVEL" \
    -l \
    "$ocd_test_log" \
    $interface_flags \
    $target_flags \
  ]

  verbose "spawning openocd: $OPENOCD $openocd_args" 1
  spawn $OPENOCD {*}$openocd_args

  tool_state_update openocd_spawn_id $spawn_id
}

proc tsuplib_internal_check_tclrpc_at_port \
    { tcl_log port max_retry_count poll_delay } {
  set ack_message "Listening on port $port for tcl connections"
  tsuplib_wait_for_acknowledge $tcl_log $ack_message $max_retry_count $poll_delay
}

proc tsuplib_internal_check_gdb_server_at_port \
    { tcl_log port max_retry_count poll_delay } {
  set ack_message "Listening on port $port for gdb connections"
  tsuplib_wait_for_acknowledge $tcl_log $ack_message $max_retry_count $poll_delay
}

proc tsuplib_wait_for_openocd_initialization {ocd_log_name tcl_port gdb_port} {

  set max_retries 150
  # TODO: looks like this should be board(type)-specific
  set poll_delay 0.2

  if {[catch {tsuplib_wait_for_file $ocd_log_name $max_retries $poll_delay} \
      ERROR_INFO]} {
    error "log-poll error: $ERROR_INFO"
  }

  if {![string match $tcl_port "none"] && \
       [catch {tsuplib_internal_check_tclrpc_at_port \
              $ocd_log_name $tcl_port $max_retries $poll_delay} \
       ERROR_INFO]} {
    # NOTE: log printing can be VERY expensive
    # puts [exec cat $ocd_log_name]
    error "OpenOCD/TclServer: $ERROR_INFO"
  }

  if {![string match $gdb_port "none"] && \
       [catch {tsuplib_internal_check_gdb_server_at_port \
              $ocd_log_name $gdb_port $max_retries $poll_delay} \
       ERROR_INFO]} {
    # NOTE: log printing can be VERY expensive
    # puts [exec cat $ocd_log_name]
    error "OpenOCD/GdbServer: $ERROR_INFO"
  }

  verbose "openocd is up and running" 1
}

proc tsuplib_shutdown_openocd { cleanup_type } {

  if {![tool_state_has openocd_spawn_id]} {
    perror "unexpected tool_finish (no openocd session is active)"
    return
  }

  set openocd_instance_spawn_id [tool_state_get openocd_spawn_id]
  if {$openocd_instance_spawn_id eq "ignore_me"} {
    tool_state_clear
    verbose "\\\\\\ ocd_finish (ignored) ///\n   _______" 1
    return
  }
  # TODO: implement proper shutdown
  # TODO2: in theory we could just call `close`, the spawned process is
  # expected (?) to get SIGHUP, however there is no guarantee that OpenOCD
  # server won't hang. This needs to be tested.
  verbose "about to kill openocd instance" 2
  exec kill -s SIGINT [exp_pid -i $openocd_instance_spawn_id ]
  # wait a little bit to allow for a clean termination
  sleep [ocd_exec_delay]
  exec kill -s SIGKILL [exp_pid -i $openocd_instance_spawn_id ]

  verbose "kill sent. closing connection to OpenOCD instance" 2
  close -i $openocd_instance_spawn_id
  verbose "kill sent. reaping (wait) the process..." 2

  # TODO: this nowait looks like a bug
  wait -nowait -i $openocd_instance_spawn_id

  verbose "wait done. openocd process is reaped" 2

  if {[string match $cleanup_type "deferred"]} {
    tool_state_update openocd_spawn_id ignore_me
  } else {
    tool_state_clear
  }
}

proc tsuplib_internal_error { msg } {
  tsuplib_disconnect_client
  error $msg
}

proc tsuplib_tclrcp_connect {} {
  # TODO: remove this global
  global spawn_id

  if {![tool_state_has openocd_spawn_id]} {
    tsuplib_internal_error "OpenOCD: no active OpenOCD instance is found (ocd_connect)"
  }
  if {[tool_state_has client_spawn_id]} {
    tsuplib_internal_error "OpenOCD: multiple connections to OpenOCD instance is not supported (ocd_connect)"
  }

  #set stty_init "-echo -isig -icanon"
  # we use raw to avoid translation of \x1a to ^D
  # -echo just disables echoing of sent symbols
  set stty_init "raw -echo"
  spawn nc localhost [tool_state_get openocd_tclrpc_port]
  tool_state_update client_spawn_id $spawn_id
  tool_state_update client_type tclrpc
  unset stty_init


  tsuplib_internal_tclrpc_send_command "echo \"Hi there!\"" capture
  expect {
    "Hi there!\n\x1a" {
      verbose "OpenOCD: connection established, all is good" 1
    }
    eof {
      tool_state_steal client_spawn_id
      wait -nowait
      tsuplib_internal_error "OpenOCD: unexpected EOF while expecting acknowledge"
    }
    timeout {
      tsuplib_internal_error "OpenOCD: could not recieve acknowledge"
    }
  }

  tsuplib_internal_tclrpc_send_command "targets" capture
  expect {
    \x1a {
      verbose "OpenOCD: targets list received" 1
    }
    eof {
      tsuplib_internal_error "OpenOCD: could not recieve targets list from OpenOCD"
    }
    timeout {
      tsuplib_internal_error "OpenOCD: unexpected timeout while waiting for initial targets listing"
    }
  }
}

proc tsuplib_internal_tclrpc_send_command {msg {mode "catch"} } {

  if {![tool_state_has client_spawn_id]} {
    tsuplib_internal_error "trying to send <$msg> without tclrpc connection"
  }

  set ocd_client_type [tool_state_get client_type]
  if {![string match $ocd_client_type "tclrpc"]} {
    tsuplib_internal_error "expecting tclrpc client type, detected: <$ocd_client_type>"
  }

  # NOTE: currently, catch_and_capture is only for debugging purposes
  if { $mode == "catch_and_capture" } {
    verbose ">>>> capture { set code \[catch { $msg } opr\] }"  2
    send "set log \[capture { set code \[catch { $msg } opr\] } \] ; set opr \"\$code:\$log\$opr\"\x1a"
  } elseif { $mode == "catch" } {
    verbose ">>>> catch { $msg } opr" 2
    send "set code \[catch { $msg } opr\] ; set opr \$code:\$opr\x1a"
  } elseif { $mode == "capture" } {
    verbose ">>>> capture { $msg }" 2
    send "capture { $msg }\x1a"
  } else {
    tsuplib_internal_error "unsupported communication mode <$mode>"
  }
}

proc tsuplib_tclrpc_run_command {msg} {
  tsuplib_internal_tclrpc_send_command $msg
  expect {
    \x1a {
      return $expect_out(buffer)
    }
    eof {
      tsuplib_internal_error "tclrpc: unexpected EOF while waiting results of <$msg>"
    }
    timeout {
      tsuplib_internal_error "tclrpc: unexpected timeout while waiting results of <$msg>"
    }
  }
}

proc tsuplib_disconnect_client { } {
  if {![tool_state_has client_spawn_id]} {
    return
  }
  set ocd_client_spawn_id [tool_state_steal client_spawn_id]

  verbose "Closing connection to OpenOCD client" 1
  close -i $ocd_client_spawn_id
  verbose "client connection closed, reaping the process" 1

  wait -nowait -i $ocd_client_spawn_id
  verbose "client connection is dead, farewell!" 1
}
