proc ocdtlb_test_resource_dir {} {
  # Note: these come from expect framework
  global srcdir
  global subdir
  return "$srcdir/$subdir/lib"
}

proc ocdtlb_test_resource_path { name } {
  set resource_path "[ocdtlb_test_resource_dir]/$name"
  if {![file exists "$resource_path"]} {
    fatalError "could not find test resource at $resource_path"
  }
  return $resource_path
}

proc ocdtlb_expect_present {where what} {
  if {[lsearch -exact $where $what] == -1} {
    error "$what NOT found"
  }
}

proc ocdtlb_expect_missing {where what} {
  if {[lsearch -exact $where $what] >= 0} {
    error "$what is unexpectedly present"
  }
}

proc ocdtlb_get_tmp_prefix {id} {
  set default_bin_prefix [tool_state_get default_bin_prefix]
  return "${default_bin_prefix}_$id"
}

proc ocdtlb_addr_add { base_address increment } {
  return [format 0x%x [expr {$base_address + $increment}]]
}

proc ocdtlb_compare_equal { left right } {
  set llen [llength $left]
  set rlen [llength $right]
  if {[expr {$llen != $rlen} ]} {
    error "length($left) != length($right)"
  }
  foreach l $left r $right {
    if { [expr { $l != $r} ] } { return 0 }
  }
  return 1
}

proc ocdtlb_expect_equal { left right } {
  if { [ ocdtlb_compare_equal $left $right ] } { return }
  error "$left != $right"
}

proc ocdtlb_compare_equal_hex { left right } {
  set scanned_left {}
  set scanned_right {}
  foreach li $left {
    scan $li %x l
    lappend scanned_left $l
  }
  foreach ri $right {
    scan $ri %x r
    lappend scanned_right $r
  }
  return [ocdtlb_compare_equal $scanned_left $scanned_right]
}

proc ocdtlb_expect_equal_hex { left right } {
  if { [ ocdtlb_compare_equal_hex $left $right ]} { return }
  error "$left != $right"
}

proc ocdtlb_unique_list {list} {
  set dict {}
  foreach item $list {
    dict set dict $item ""
  }
  dict keys $dict
}

proc ocdtlb_rsp_get { response {what value} } {
  if {![response_is_success $response]} {
    error "can not get value from failed response: $response"
  }
  if {![dict exists $response $what]} {
    error "$what does not exists in: $response"
  }
  return [dict get $response $what]
}

proc ocdtlb_do_get_target_status {} {
  set response [ocdtlb_run_expect "targets"]

  set active_idx [ocdtlb_rsp_get $response active_idx]
  set states     [ocdtlb_rsp_get $response states]
  set active_state [lindex $states $active_idx]
  return $active_state
}

proc ocdtlb_do_expect_halted {} {
  set active_state [ocdtlb_do_get_target_status]
  if {![string match $active_state "halted"]} {
    error "$active_state is not halted"
  }
  return
}

proc ocdtlb_do_expect_running {} {
  set active_state [ocdtlb_do_get_target_status]
  if {![string match $active_state "running"]} {
    error "$active_state is not running"
  }
  return
}

# TODO: rename to do_expect
proc ocdtlb_do_byte_read_compare { base_addr expected_values } {
  set addr $base_addr
  foreach expected_byte $expected_values {
    set response [ocdtlb_run_expect "mdb $addr"]
    set read_value [dict get $response data]
    if { [expr { $expected_byte != $read_value}] } {
      error "$expected_byte != $read_value at @$addr"
    }
    set addr [ocdtlb_addr_add $addr 1]
  }
}

proc octdlb_wait_resume { {scale 1} } {
  set resume_delay [ocd_resume_delay]
  set scaled_delay [expr $resume_delay * $scale]
  verbose "resume wait for $scaled_delay seconds" 3
  sleep $scaled_delay
}

# NOTE: this function always does at least one step
proc ocdtlb_do_expect_step_until { end_address iteration_limit } {
  set count 0
  while 1 {
    ocdtlb_run_expect "step"
    set cur_pc [ocdtlb_rsp_get [ocdtlb_run_expect "reg pc"]]
    if { [ocdtlb_compare_equal_hex $cur_pc $end_address]} {
      return
    }
    incr count
    if { [expr { $count > $iteration_limit } ] } {
      error "could not reach $end_address, tried $count steps"
    }
  }
}

proc ocdtlb_run_expect_raw {command parser_name {expect_op_fail 0}} {
  verbose "cmd: ${command}" 1

  set response [tsuplib_tclrpc_run_command $command]
  verbose "\nRESPONSE:\n    $response\n" 3

  set status [string range $response 0 1]
  # command can idicate an abnormal termination if something goes wrong
  if { $status != "0:" } {
    if { $expect_op_fail == 0 } {
      error "abnormal op termination"
    }
    return [internal_parse_error "ABORT" $response {}]
  }

  # Now we assume that the command properly returned a result
  # Note: the result interpretation is still determined by the parser
  set body [string replace $response 0 1]

  if { [catch { $parser_name $body } parsed] } {
    error $parsed
  }

  # now we assume that we have a properly parsed result
  if { ($expect_op_fail == 0) && ![response_is_success $parsed] } {
    error "unexpected response failure"
  }
  if { ($expect_op_fail != 0) && [response_is_success $parsed] } {
    error "expecting op_failure"
  }

  return $parsed
}

proc ocdtlb_run_expect {command {expect_op_fail 0} } {
  set pruned_cmd [string trim $command]
  if {[llength [split $pruned_cmd "\n"]] != 1} {
    error "multiline commands are not supported ($command)"
  }
  # We do not support commands that have ';' inside
  if {[llength [split $pruned_cmd ";"]] != 1} {
    error "possible multi-command is not supported ($command), use _raw call"
  }
  set parser parse_none
  switch -nocase -regexp -- $pruned_cmd {
    {^targets +[^ ]+$}      { set parser parse_targets_set }
    {^targets$}             { set parser parse_targets_listing }
    {^halt$}                { set parser parse_halt }
    {^resume +[^ ]+$}       { set parser parse_resume }
    {^resume$}              { set parser parse_resume }
    {^reset +[^ ]+$}        { set parser parse_reset }
    {^reset$}               { set parser parse_reset }
    {^load_image +[^ ]+}    { set parser parse_load_image }
    {^dump_image +[^ ]+}    { set parser parse_dump_image }
    {^read_memory +[^ ]+}   { set parser parse_memory_read_response }
    {^write_memory +[^ ]+}  { set parser parse_memory_write_response }
    {^set_reg +[^ ]+}       { set parser parse_reg_set }
    {^reg +[^ ]+ +[^ ]+$}   { set parser parse_reg_set }
    {^reg +[^ ]+$}          { set parser parse_reg_fetch }
    {^reg$}                 { set parser parse_regfile_listing }
    {^step +[^ ]+$}         { set parser parse_step }
    {^step$}                { set parser parse_step }
    {^mdb +[^ ]+}           { set parser parse_memd_response }
    {^mdh +[^ ]+}           { set parser parse_memd_response }
    {^mdw +[^ ]+}           { set parser parse_memd_response }
    {^mdd +[^ ]+}           { set parser parse_memd_response }
    {^mwb +[^ ]+}           { set parser parse_memw_response }
    {^mwh +[^ ]+}           { set parser parse_memw_response }
    {^mww +[^ ]+}           { set parser parse_memw_response }
    {^mwd +[^ ]+}           { set parser parse_memw_response }
    {^bp$}                  { set parser parse_bp_listing }
    {^bp +[^ ]+}            { set parser parse_bp }
    {^rbp +[^ ]+}           { set parser parse_rbp }
    {^wp$}                  { set parser parse_wp_listing }
    {^wp +[^ ]+ +[0-9]}     { set parser parse_wp_set }
    {^rwp +[^ ]+}           { set parser parse_wp_clear }
    {^smp$}                 { set parser parse_smp_status }
    {^smp +[^ ]+}           { set parser parse_smp_update }
    {^irscan +[^ ]+}        { set parser parse_irscan }
    {^drscan +[^ ]+}        { set parser parse_drscan }
    {^scan_chain}           { set parser parse_scan_chain }
    {^runtest +[^ ]+}       { set parser parse_runtest }
    {^wait_halt$}           { set parser parse_wait_halt }
    {^poll$}                { set parser parse_poll }
    default {
      error "could not select parser for ($command), consider using *_raw call"
    }
  }
  return [ocdtlb_run_expect_raw $command $parser $expect_op_fail]
}

proc ocd_test_pass {} {
  pass [tool_state_get test_name]
}

proc ocd_test_fail {} {
  fail [tool_state_get test_name]
}

proc ocd_test_untested {} {
  untested [tool_state_get test_name]
}

proc ocd_test_unresolved {} {
  unresolved [tool_state_get test_name]
}

proc ocd_test_unsupported {} {
  unsupported [tool_state_get test_name]
}

proc ocd_test_xfail {} {
  xfail [tool_state_get test_name]
}

proc ocd_compile_executable { src_name outputname { extra_flags {} } } {
  # Note: these come from expect framework
  global srcdir
  global subdir

  set additional_flags [list \
    debug \
    additional_flags=-Xlinker \
    additional_flags=-Map=$outputname.map \
  ]
  foreach add_flag $extra_flags {
    lappend additional_flags additional_flags=$add_flag
  }
  set result [target_compile \
    "$srcdir/$subdir/$src_name" \
    "$outputname" \
    "executable" \
    $additional_flags \
  ]
  if {![string match $result ""]} {
    error "could not compile executable ($src_name->$outputname): $result"
  }
  describe_program "$outputname"
  return $result
}

