proc run_test {} {
    if {[target_info cpu,xlen] != 64} {
        return [ocd_test_unsupported]
    }

    set available_modes [list sv39 sv48 sv57]
    set modes [list]

    foreach mode $available_modes {
        if {[target_info "cpu,$mode"]} {
            lappend modes $mode
        }
    }

    if {[llength $modes] == 0} {
        return [ocd_test_unsupported]
    }

    set lib_translate_support [ocdtlb_test_resource_path lib_translate_support.tcl]
    source $lib_translate_support

    set VA_OFFSET 0xa0000
    set PA_OFFSET 0x10000

    set default_bin_prefix [tool_state_get default_bin_prefix]
    ocd_compile_executable "lib/memory.S" "$default_bin_prefix.exe"

    set expected_data 0xdeadbeef

    set table_addr [tool_state_get_program_symbol _entry]
    set virtual_address 0x[format %x [expr {${table_addr} + ${VA_OFFSET} }]]
    set physical_address 0x[format %x [expr {${table_addr} + ${PA_OFFSET} }]]

    set va_list [list $virtual_address]
    set pa_list [list $physical_address]

    ocd_connect

    foreach mode $modes {
        verbose "testing $mode translation mode" 1

        ocdtlb_run_expect "reset halt"

        init_with_config $mode $table_addr $va_list $pa_list
        turn_on_translation $mode $table_addr

        ocdtlb_run_expect "mdw $virtual_address"

        ocdtlb_run_expect "mww phys $physical_address $expected_data"
        set data [dict get [ocdtlb_run_expect "mdw $virtual_address"] data]
        ocdtlb_expect_equal $data $expected_data

        ocdtlb_run_expect "mww $virtual_address $expected_data"
        set data [dict get [ocdtlb_run_expect "mdw phys $physical_address"] data]
        ocdtlb_expect_equal $data $expected_data
    }

    return [ocd_test_pass]
}

return [run_test]
