proc run_test {} {
    if {[target_info cpu,xlen] != 64} {
        return [ocd_test_unsupported]
    }

    set available_modes [list sv39 sv48 sv57]
    set available_modes_x4 [list sv39x4 sv48x4 sv57x4]
    set modes [list]
    set modes_x4 [list]

    foreach mode $available_modes mode_x4 $available_modes_x4 {
        if {[target_info "cpu,$mode"] && [target_info "cpu,$mode_x4"]} {
            lappend modes $mode
            lappend modes_x4 $mode_x4
        }
    }

    if {[llength $modes] == 0} {
        return [ocd_test_unsupported]
    }


    set lib_translate_support [ocdtlb_test_resource_path lib_translate_support.tcl]
    source $lib_translate_support

    set VA_OFFSET 0xa0000
    set PA_OFFSET 0xc0000
    set X4_TABLE_OFFSET 0x8000
    set GA_OFFSET 0xb0000

    set default_bin_prefix [tool_state_get default_bin_prefix]
    ocd_compile_executable "lib/memory.S" "$default_bin_prefix.exe"

    set expected_data 0xdeadbeef

    set table_addr [tool_state_get_program_symbol _entry]
    set table_addr_x4 0x[format %x [expr {$table_addr + ${X4_TABLE_OFFSET} }]]
    set virtual_address 0x[format %x [expr {$table_addr + ${VA_OFFSET} }]]
    set guest_address 0x[format %x [expr {$table_addr + ${GA_OFFSET}} ]]
    set physical_address 0x[format %x [expr {$table_addr + ${PA_OFFSET} }]]

    set va_list [list $virtual_address]
    set ga_list [list $guest_address]

    set extended_ga_list [list $guest_address]
    set pa_list [list $physical_address]

    for {set i 0} {$i < 8} {incr i} {
        set pte 0x[format %x [expr {$table_addr + $i * 0x1000}]]
        lappend extended_ga_list $pte
        lappend pa_list $pte
    }

    ocd_connect

    foreach mode $modes {
        foreach mode_x4 $modes_x4 {
            ocdtlb_run_expect "reset halt"

            init_with_config $mode $table_addr $va_list $ga_list
            init_with_config $mode_x4 $table_addr_x4 $extended_ga_list $pa_list

            turn_on_translation $mode $table_addr 1
            turn_on_translation $mode_x4 $table_addr_x4

            ocdtlb_run_expect "mdw $virtual_address"

            ocdtlb_run_expect "mww phys $physical_address $expected_data"
            set data [dict get [ocdtlb_run_expect "mdw $virtual_address"] data]
            ocdtlb_expect_equal $data $expected_data

            ocdtlb_run_expect "mww $virtual_address $expected_data"
            set data [dict get [ocdtlb_run_expect "mdw phys $physical_address"] data]
            ocdtlb_expect_equal $data $expected_data
        }
    }

    return [ocd_test_pass]
}

return [run_test]
