set_board_info cpu,xlen 32
set_board_info cpu,has_floats 1
set_board_info cpu,has_doubles 1
set_board_info cpu,has_u_mode 1
set_board_info cpu,has_s_mode 1
set_board_info cpu,has_h_ext 0

set_board_info cpu,has_v_ext 0
set_board_info cpu,v_ext_vlen 0
set_board_info cpu,v_ext_elen 0
set_board_info cpu,v_ext_misa_writable 0

set_board_info cpu,trigger_count 5

set_board_info cpu,has_watchpoints 1
set_board_info cpu,has_watchpoints_equal 1
set_board_info cpu,has_watchpoints_napot 1
set_board_info cpu,has_watchpoints_gelt 1
set_board_info cpu,has_watchpoints_data_mask 0
set_board_info cpu,wp_eq_matches_on_crossing 0
set_board_info cpu,wp_napot_matches_on_crossing 1
set_board_info cpu,wp_gelt_matches_on_crossing 1

set_board_info cpu,sv32 0
set_board_info cpu,sv39 0
set_board_info cpu,sv48 0
set_board_info cpu,sv57 0

set_board_info cpu,sv32x4 0
set_board_info cpu,sv39x4 0
set_board_info cpu,sv48x4 0
set_board_info cpu,sv57x4 0

set_board_info cpu,misaligned_access_support 0

set_board_info cpu,dm_run_read_pc 1

set_board_info cpu,dm_abstract_csr 1
set_board_info cpu,dm_abstract_fpr 1
set_board_info cpu,dm_is_slow 0

set_board_info cpu,dm_sba_access_enable 0

add_board_info cflags   -march=rv32gc
add_board_info cflags   -mabi=ilp32d
