#!/usr/bin/expect

set STAND_NAME [lindex $argv 0]
set PLATFORM [lindex $argv 1]

catch {system killall -9 openocd}
catch {system killall -9 vivado_lab}
catch {system killall -9 hw_server}
catch {system rm /home/stand/hw_server.log}

system /home/stand/hw_server.sh

set timeout 120

# check if platform starts with "/"
if {[string first / $PLATFORM] == 0} {
  spawn [pwd]/fpga.sh bit $STAND_NAME $PLATFORM
} else {
  spawn [pwd]/fpga.sh set $STAND_NAME $PLATFORM
}

expect {
  "Setting Platform complete!" {
    puts "bitstream instantiated!"
  }
  eof {
    error "unexpected EOF (waiting for device programming)"
  }
  timeout {
    error "unexpected timeout (waiting for device programming)"
  }
}
