proc run_test {} {
  global GPR

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "missing_reg_faults.S" "$default_bin_prefix.exe"

  # created by compile executable
  set ENTRY_ADDR [tool_state_get_program_symbol _entry]
  set MAIN_ADDR [tool_state_get_program_symbol main]
  set END_ADDR [tool_state_get_program_symbol end]

  ocd_connect

  ocdtlb_run_expect "halt"
  ocdtlb_run_expect "load_image $default_bin_prefix.exe"
  ocdtlb_run_expect "reg pc $ENTRY_ADDR"
  ocdtlb_run_expect "resume"

  octdlb_wait_resume

  ocdtlb_run_expect "halt"

  set expect_op_failure 1
  ocdtlb_run_expect "reg wobble 0xdeadbee" $expect_op_failure

  # now check that the target is still responsive
  set STEP_LIMIT 100
  ocdtlb_do_expect_step_until $MAIN_ADDR $STEP_LIMIT

  ocdtlb_do_expect_step_until $END_ADDR $STEP_LIMIT
  set reg_prev [ocdtlb_rsp_get [ocdtlb_run_expect "reg $GPR(1)"]]

  ocdtlb_do_expect_step_until $END_ADDR $STEP_LIMIT
  set reg_cur [ocdtlb_rsp_get [ocdtlb_run_expect "reg $GPR(1)"]]

  if {![expr ($reg_cur - $reg_prev) == 1]} {
    perror "unexpected GPR value after iteration cycle: prev = $reg_prev, cur = $reg_cur"
    return [ocd_test_fail]
  }

  return [ocd_test_pass]
}

return [run_test]


