proc run_test {} {
  ocd_connect

  ocdtlb_run_expect "reset halt"

  set rs [ocdtlb_run_expect "reg"]

  set found_registers [ocdtlb_rsp_get $rs found_name]

  if {([target_info openocd,hidden_triggers] == 1) || \
      ([target_info openocd,ide_cloak] == 1) } {
    set TRIGGER_CSR_PRESENT EXPECT_ABSENT
    set TRIGGER_CSR_ACCESS ACCESS_SUCCESS
  } else {
    set TRIGGER_CSR_PRESENT EXPECT_PRESENT
    set TRIGGER_CSR_ACCESS ACCESS_SUCCESS
  }

  if {[target_info openocd,extra_csr] == 1} {
    set EXTRA_CSR_PRESENT EXPECT_PRESENT
    set RENAMED_CSR_ACCESS ACCESS_FAIL
  } else {
    set EXTRA_CSR_PRESENT EXPECT_ABSENT
    set RENAMED_CSR_ACCESS ACCESS_FAIL
  }

  # name, present_status, access_attempt
  # invalid_rename - is an attempt to rename existing register
  # csr2048 - default name for some exposed csr
  # csr_some_register - renamed exposed csr (non-default name)
  set EXPOSED_CSR [list \
    tselect $TRIGGER_CSR_PRESENT $TRIGGER_CSR_ACCESS \
    tdata1 $TRIGGER_CSR_PRESENT $TRIGGER_CSR_ACCESS \
    invalid_rename EXPECT_ABSENT ACCESS_FAIL \
    csr2048 $EXTRA_CSR_PRESENT ACCESS_FAIL \
    csr_some_register $EXTRA_CSR_PRESENT ACCESS_FAIL \
    csr2050 $EXTRA_CSR_PRESENT ACCESS_FAIL \
    csr_some_register_hex $EXTRA_CSR_PRESENT ACCESS_FAIL \
  ]

  foreach {reg_name is_present expected_access} $EXPOSED_CSR {
    verbose "checking $reg_name: $is_present/$expected_access" 1
    if {[string match $is_present EXPECT_PRESENT]} {
      ocdtlb_expect_present $found_registers $reg_name
    } else {
      ocdtlb_expect_missing $found_registers $reg_name
    }

    if {[string match $expected_access ACCESS_SUCCESS]} {
      ocdtlb_run_expect "reg $reg_name"
    } else {
      if {![catch ocdtlb_run_expect "reg $reg_name"]} {
        error "undexpected ACCESS_SUCCESS for $reg_name read"
      }
    }
  }

  return [ocd_test_pass]
}

return [run_test]

