proc run_test {} {
  ocd_connect
  # disconnect and kill the default openocd
  ocd_manual_finish

  proc ocd_launch_script { tcl_script } {
    global OPENOCD
    global OPENOCD_ROOT
    global srcdir
    global subdir

    set default_bin_prefix [tool_state_get default_bin_prefix]
    # TODO: env is unused for now
    set openocd_adapter_flags [standInfoGetInterfaceFlags]

    set target_cfg_flags [list \
      -f ${OPENOCD_ROOT}/share/openocd/scripts/target/syntacore_target.cfg \
    ]

    set test_script_flags [list \
     -f $srcdir/$subdir/universal_config_tests/$tcl_script \
    ]

    set cmd [concat \
      [list $OPENOCD] \
      $openocd_adapter_flags \
      $target_cfg_flags \
      [list -f $srcdir/$subdir/universal_config_tests/common_test_init.tcl] \
      $test_script_flags \
    ]
    # [list -d2]

    set NCORES [target_info cpu,cores_num]
    set ::env(NCORES) $NCORES
    if { [target_info sim] eq "" } {
      set ::env(IS_SIM) 0
    } else {
      set ::env(IS_SIM) 1
    }

    verbose $cmd 1
    eval exec -ignorestderr $cmd 2>> ${default_bin_prefix}_${tcl_script}.log
  }

  ocd_launch_script not_testable.tcl
  ocd_launch_script chipname_test.tcl
  ocd_launch_script harts_num_test.tcl
  ocd_launch_script hooks_test.tcl
  ocd_launch_script work_area_enable.tcl
  ocd_launch_script work_area_disable.tcl
  ocd_launch_script reset_config_test.tcl
  ocd_launch_script reset_config_test2.tcl
  ocd_launch_script defaults.tcl

  # return [ocd_test_pass]
  pass universal_config
}

return [run_test]
