proc compile_boot_code { output_name } {
  set boot_source "[get_support_file sim/spike_boot.S]"
  return [target_compile $boot_source "$output_name" "executable" {}]
}

proc ${board}_initialization_abort { msg } {
  perror $msg
  error "could not initialize simulator board"
}

proc spike_get_target_memory_map {} {
  set primary_region "0x80000000:0xa00000"
  if { [target_info memory,has_high_pa]} {
    set primary_region "0x80000000:0xffffffff80000000"
  }
  if { [target_info memory,ocd_work_area]} {
    return "-m0x3ff0000:0x10000,$primary_region"
  }
  return "-m$primary_region"
}

proc init_sim_args { boot_binary } {
  set sim_options [target_info sim,options]

  if {[target_info cpu,xlen] == 64} {
    set isa_substring "rv64gc"
    set replacement_substring "rv64gch"
  } else {
    set isa_substring "rv32gc"
    set replacement_substring "rv32gch"
  }

  set list_index [lsearch -regexp $sim_options $isa_substring]

  if {[target_info cpu,has_h_ext]} {
    if {$list_index != -1} {
      set isa [lindex $sim_options $list_index]

      set substring_for_replace_start [string first $isa_substring $isa]
      set substring_for_replace_end [expr {$substring_for_replace_start + [string length $isa_substring] - 1}]

      set changed_isa [string replace $isa $substring_for_replace_start $substring_for_replace_end $replacement_substring]

      set sim_options [lreplace $sim_options $list_index $list_index $changed_isa]
    } else {
      error "Can't find position to insert \"h\" (hypervisor extension) to $isa"
    }
  }

  return [list {*}$sim_options \
                     [spike_get_target_memory_map] \
                     $boot_binary]
}

proc ${board}_init { name } {
  global SPIKE_SIM
  global spike_board_spawn_id

  verbose "opening board $name" 1
  if {[info exists spike_board_spawn_id]} {
    ${name}_initialization_abort "unexepcted board id detected"
  }
  set boot_binary boot_$name.elf
  if  { [compile_boot_code $boot_binary] != "" } {
    ${name}_initialization_abort "could not compile boot binary"
  }
  verbose "boot code compiled successfully" 2

  set sim_args [init_sim_args $boot_binary]

  verbose "running spike: $SPIKE_SIM $sim_args" 1
  spawn $SPIKE_SIM {*}$sim_args

  set rbb_port 0

  expect {
    -re {Listening for remote bitbang connection on port ([1-9][0-9]*).} {
      set rbb_port $expect_out(1,string)

      verbose "spike launched successfully" 1
      set spike_board_spawn_id $spawn_id
    }
    eof {
      ${name}_initialization_abort "could not initialize spike for $name board"
    }
    timeout {
      ${name}_initialization_abort "no acknowledge from $name board"
    }
  }

  spike_update_active_rbb_port $rbb_port
}

proc ${board}_close { name } {
  global spike_board_spawn_id

  verbose "closing board $name" 1

  if {![info exists spike_board_spawn_id]} {
    ${name}_initialization_abort "could not detect active board"
  }

  verbose "killing spike board for $name" 2
  exec kill -9 [exp_pid -i $spike_board_spawn_id]

  verbose "closing connection to the board..." 2
  close -i $spike_board_spawn_id

  verbose "board is killed, reaping..." 2
  wait -nowait -i $spike_board_spawn_id
  unset spike_board_spawn_id

  verbose "spike board $name is closed, bye!" 1
}

proc spike_update_active_rbb_port { value } {
  global RBB_PORT
  set RBB_PORT $value
  verbose "rbb_port: $value" 1
}

proc spike_get_active_rbb_port {} {
  global RBB_PORT
  return $RBB_PORT
}

