proc compile_boot_code { output_name } {
  set boot_source "[get_support_file sim/spike_boot.S]"
  return [target_compile $boot_source "$output_name" "executable" {}]
}

proc ${board}_initialization_abort { msg } {
  perror $msg
  error "could not initialize simulator board"
}

proc spike_get_target_memory_map {} {
  set primary_region "0x80000000:0xa00000"
  if { [target_info memory,has_high_pa]} {
    set primary_region "0x80000000:0xffffffff80000000"
  }
  if { [target_info memory,ocd_work_area]} {
    return "-m0x3ff0000:0x10000,$primary_region"
  }
  return "-m$primary_region"
}

proc isa_string_for_current_target {} {
  # the isa string is derived from:
  #   - target_info cpu,* : basic properties that can be used to form an isa string
  #   - `sim,ext_isa_info` : extensions that we want to enable
  # In general, the intention to construct isa string as --isa=<base_isa>_<ext>
  # <base_isa> should be formed from `cpu,*` properties and extentions are
  # just appended as is.
  # if the first element of `sim,ext_isa_info` starts from rv*, we use it as a
  # <base_isa> as is ignoring all `cpu,*` properties our target has

  # construct <base_isa> part of the isa string
  set base_isa "rv"
  set xlen [target_info cpu,xlen]
  if {$xlen == 64} {
    set base_isa "${base_isa}64"
  } elseif {$xlen == 32} {
    set base_isa "${base_isa}32"
  } else {
    error "unsupported XLEN=$xlen specified for the board"
  }
  # TODO: for now we always assume that we have "gc" target, needs to be fixed
  set base_isa "${base_isa}gc"
  if {[target_info cpu,has_v_ext]} {
    set base_isa "${base_isa}v"
  }
  if {[target_info cpu,has_h_ext]} {
    set base_isa "${base_isa}h"
  }

  # now construct <ext> part, optionally overriding <base_isa>
  set ext_isa_info [target_info sim,ext_isa_info]
  if {[llength $ext_isa_info] > 0} {
    if {[string first "rv" [lindex $ext_isa_info 0]] == 0} {
      set base_isa [lindex $ext_isa_info 0]
      set ext_isa_info [lreplace $ext_isa_info 0 0]
    }
  }
  # NOTE: currently all our spike platforms are assumed to support zicntr
  lappend ext_isa_info zicntr
  set ext_isa [join $ext_isa_info "_"]

  set final_isa_string $base_isa
  if {[string length $ext_isa] > 0} {
    set final_isa_string "${final_isa_string}_${ext_isa}"
  }

  return $final_isa_string
}

proc init_sim_args { boot_binary } {
  set isa_string [isa_string_for_current_target]

  verbose "Final ISA string for simulator target: $isa_string" 1
  set sim_options [list --isa=$isa_string {*}[target_info sim,options]]
  return [list {*}$sim_options [spike_get_target_memory_map] $boot_binary]
}

proc ${board}_init { name } {
  global SPIKE_SIM
  global spike_board_spawn_id

  verbose "opening board $name" 1
  if {[info exists spike_board_spawn_id]} {
    ${name}_initialization_abort "unexepcted board id detected"
  }
  set boot_binary boot_$name.elf
  if  { [compile_boot_code $boot_binary] != "" } {
    ${name}_initialization_abort "could not compile boot binary"
  }
  verbose "boot code compiled successfully" 2

  set sim_args [init_sim_args $boot_binary]

  verbose "running spike: $SPIKE_SIM $sim_args" 1
  spawn $SPIKE_SIM {*}$sim_args

  set rbb_port 0

  expect {
    -re {Listening for remote bitbang connection on port ([1-9][0-9]*).} {
      set rbb_port $expect_out(1,string)

      verbose "spike launched successfully" 1
      set spike_board_spawn_id $spawn_id
    }
    eof {
      ${name}_initialization_abort "could not initialize spike for $name board"
    }
    timeout {
      ${name}_initialization_abort "no acknowledge from $name board"
    }
  }

  spike_update_active_rbb_port $rbb_port
}

proc ${board}_close { name } {
  global spike_board_spawn_id

  verbose "closing board $name" 1

  if {![info exists spike_board_spawn_id]} {
    ${name}_initialization_abort "could not detect active board"
  }

  verbose "killing spike board for $name" 2
  exec kill -9 [exp_pid -i $spike_board_spawn_id]

  verbose "closing connection to the board..." 2
  close -i $spike_board_spawn_id

  verbose "board is killed, reaping..." 2
  wait -nowait -i $spike_board_spawn_id
  unset spike_board_spawn_id

  verbose "spike board $name is closed, bye!" 1
}

proc spike_update_active_rbb_port { value } {
  global RBB_PORT
  set RBB_PORT $value
  verbose "rbb_port: $value" 1
}

proc spike_get_active_rbb_port {} {
  global RBB_PORT
  return $RBB_PORT
}

