proc run_test {} {
  global srcdir
  global subdir

  set BinFile "$srcdir/$subdir/lib/BINARY_FILE.bin"
  set ElfFile "[tool_state_get default_bin_prefix]_spike_run.elf"
  ocd_compile_executable "lib/simple.S" "$ElfFile"

  set LOAD_ADDR [tool_state_get_program_symbol load_address]
  set ENTRY_ADDR [tool_state_get_program_symbol _entry]

  set script_to_run "$srcdir/$subdir/lib/fpga_lib_test.tcl"
  set script_timeout_multiplier 10
  set LogFile [utils_spawn_universal_launcher \
    [list --load-extra-scripts \
      --run-script $script_to_run \
      --run-command \
        "run_test_with_elf_and_bin $BinFile $ElfFile $LOAD_ADDR $ENTRY_ADDR"] \
    fpga_lib_test \
    expect_success \
    $script_timeout_multiplier]

  return [ocd_test_pass]
}

return [run_test]

