proc run_test {} {
  set script_to_run [ocdtlb_test_resource_path fpga_verbosity_test.tcl]
  set script_timeout_multiplier 10
  set LogFile [utils_spawn_universal_launcher \
    [list \
      --verbose \
      --run-script $script_to_run \
      --run-command "run_verbosity_test"] \
    fpga_lib_pmu_test \
    expect_success \
    $script_timeout_multiplier]

  return [ocd_test_pass]
}

return [run_test]



