proc run_test {} {
  set ElfFile "[tool_state_get default_bin_prefix]_spike_run.elf"
  ocd_compile_executable "lib/simple.S" "$ElfFile"

  set ENTRY_ADDR [tool_state_get_program_symbol _entry]

  set script_to_run [ocdtlb_test_resource_path fpga_lib_read_write_reg_test.tcl]
  set script_timeout_multiplier 10
  set LogFile [utils_spawn_universal_launcher \
    [list \
      --verbose \
      --run-script $script_to_run \
      --run-command \
        "run_read_write_reg_test $ElfFile $ENTRY_ADDR [target_info cpu,xlen]"] \
    fpga_lib_read_write_reg \
    expect_success \
    $script_timeout_multiplier]

  return [ocd_test_pass]
}

return [run_test]

