set target_triplet     "riscv64-unknown-elf"

#TODO: looks like unused
set LDFLAGS_FOR_TARGET ""
set CFLAGS_FOR_TARGET  ""

if {![info exist OPENOCD_ROOT]} {
  set OPENOCD_ROOT $env(OPENOCD_ROOT)
} else {
  verbose "using OPENOCD_ROOT from local config: $OPENOCD_ROOT" 1
}

if {![info exist SPIKE_SIM]} {
  set SPIKE_SIM "spike"
} else {
  verbose "using SPIKE_SIM from local config: $SPIKE_SIM" 1
}

if {![info exist GDB_BIN]} {
  set GDB_BIN riscv64-unknown-elf-gdb
} else {
  verbose "using GDB_BIN from local config: $GDB_BIN" 1
}

if {![info exists CC_FOR_TARGET]} {
  set CC_FOR_TARGET riscv64-unknown-elf-gcc
} else {
  verbose "using CC_FOR_TARGET from local config: $CC_FOR_TARGET" 1
}

set OPENOCD "${OPENOCD_ROOT}/bin/openocd"
set OPENOCD_LOG_LEVEL 3
# enables exp_internal . That is enables internal debug of expect
set ENABLE_EXP_INTERNAL 0

set RUN_OCD_INTERNAL_ON_HW 0

set SPIKE_BITBANG 7777

set OCD_PORT_TCLRPC 6666
set OCD_PORT_GDBSRV 3333

# NOTE: environment queries below are not conventional, but should work
# fine for OpenOCD testing
puts "Checking for testsuite requirements..."
if {[auto_execok $OPENOCD] == ""} {
  puts "ERROR: could not find openocd binary at $OPENOCD"
  puts "   check your OPENOCD_ROOT ($OPENOCD_ROOT) is specified correctly"
  exit 1
}

if {[auto_execok $CC_FOR_TARGET] == ""} {
  puts "ERROR: could not find target compiler ($CC_FOR_TARGET), check your PATH"
  exit 1
} else {
  puts "WARNING: PATH is modified to contain the location of the compiler"
  # NOTE: this may require some special handling since this call won't work
  # on windows. However we don't care since the infrastructure is Linux-only
  set ::env(PATH) "$::env(PATH):[file dirname [auto_execok $CC_FOR_TARGET]]"
}

if {[auto_execok $GDB_BIN]== "" } {
  puts "ERROR: could not find GDB for target ($GDB_BIN), check your PATH"
  exit 1
}

if {[auto_execok $SPIKE_SIM] == ""} {
  puts "WARNING: could not detect $SPIKE_SIM simulator in PATH"
} else {
  set target_list {
    spike32_dmp6a0
    spike32_dmp6a0_extra_CSR
    spike32_dmp6a0_noabstractCSR
    spike32_dmp6a0_noabstractCSRFPR
    spike32_dmp6a0_noabstractFPR
    spike32_dmp6a32
    spike32_ide_cloak
    spike64_dmp6a0
    spike64_dmp6a0_extra_CSR
    spike64_dmp6a0_hidden_triggers
    spike64_dmp6a0_with_high_pa
    spike64_dmp6a64
    spike64_ide_cloak
    spike64_rvv_dmp6a0
    spike64_rvv_dmp6a0_noabstractCSR
    spike64_rvv_dmp6a0_noabstractCSRFPR
    spike64_rvv_dmp6a0_noabstractFPR
    spike64mcore4_rthw0_dmp6a0
    spike64mcore4_rthw4_dmp6a0
    spike64smp4_rthw1_dmp6a0
    spike64smp4_rthw4_dmp6a0
  }
}

