proc run_test {} {
  # This test targets gdb interaction with SMP targets
  set NUM_CORES [target_info cpu,cores_num]
  set default_bin_prefix [tool_state_get default_bin_prefix]

  ocd_compile_executable "smp.S" "$default_bin_prefix.exe" [list -DNCORES=$NUM_CORES]

  # created by compile executable
  set ENTRY_ADDR [tool_state_get_program_symbol _entry]
  set END_ADDRESS [tool_state_get_program_symbol master_loop]
  set END_SLAVE [tool_state_get_program_symbol slave_loop]
  set RENDEZVOUS_ADDRESS [tool_state_get_program_symbol rendezvous_point]

  ocd_connect

  ocdtlb_run_expect "reset halt"
  ocdtlb_run_expect "load_image $default_bin_prefix.exe"

  for { set i 0}  {$i < $NUM_CORES} {incr i} {
    ocdtlb_run_expect "targets $i"
    ocdtlb_run_expect "reg pc $ENTRY_ADDR"
  }
  ocdtlb_run_expect "bp $END_ADDRESS 4"

  # ON SMP targets resume will "resume" all targets at once
  if {[target_info openocd,smp_target]} {
    ocdtlb_run_expect "resume"
  } else {
    for { set i 0}  {$i < $NUM_CORES} {incr i} {
      ocdtlb_run_expect "targets $i"
      ocdtlb_run_expect "resume"
    }
  }

  ocdtlb_wait_resume wait_halt

  set tgts [ocdtlb_run_expect "targets"]
  set states [ocdtlb_rsp_get $tgts states]
  if {[llength $states] != $NUM_CORES} {
    perror "unexpected number of targets detected"
    return [ocd_test_fail]
  }

  # ON SMP targets all targets are expected to be halted even if only 1 thread
  # actually hits the bp

  if {[target_info openocd,smp_target]} {
    foreach state $states {
      if {![string match "halted" $state]} {
        perror "unexpected non-halted core encountered"
        return [ocd_test_fail]
      }
    }
  } else {
    set HALTED_COUNT 0
    set RUNNING_COUNT 0
    for { set i 0}  {$i < $NUM_CORES} {incr i} {
      if {[lindex $states $i] == "halted"} {
        incr HALTED_COUNT
      } else {
        incr RUNNING_COUNT
        ocdtlb_run_expect "targets $i"
        ocdtlb_run_expect "halt"
      }
    }

    if {[expr $RUNNING_COUNT != ($NUM_CORES - 1)]} {
      perror "unexpected number of running threads: $states"
      return [ocd_test_fail]
    }

    if {$HALTED_COUNT != 1} {
      perror "unexpected number of halted threads: $states"
      return [ocd_test_fail]
    }
  }

  set SLAVE_COUNT 0
  set MASTER_COUNT 0
  for { set i 0}  {$i < $NUM_CORES} {incr i} {
    ocdtlb_run_expect "targets $i"
    set pc [ocdtlb_rsp_get [ocdtlb_run_expect "reg pc"]]
    if {$pc == $END_SLAVE} {
      incr SLAVE_COUNT
    }
    if {$pc == $END_ADDRESS} {
      incr MASTER_COUNT
    }
  }

  if {[expr $SLAVE_COUNT != ($NUM_CORES - 1)]} {
    perror "unexpected number($SLAVE_COUNT) of slave cores observed"
    return [ocd_test_fail]
  }

  if {$MASTER_COUNT != 1} {
    perror "unexpected number($MASTER_COUNT) of master cores observed"
    return [ocd_test_fail]
  }

  return [ocd_test_pass]
}

return [run_test]
