proc run_test {} {
    if {![target_info cpu,has_watchpoints]} {
        return [ocd_test_unsupported]
    }

    set max_trigger_count [target_info cpu,trigger_count]
    set wp_address 0x0

    ocd_connect

    ocdtlb_run_expect "targets 0"
    ocdtlb_run_expect "reset halt"

    for {set n 0} {$n < $max_trigger_count} {incr n} {
        if {[catch {ocdtlb_run_expect "wp $wp_address 4"} var]} {
            break
        }

        set wp_address 0x[format %x [expr {$wp_address + 4}]]
    }

    set response [ocdtlb_run_catch_and_capture "wp $wp_address 4"]
    ocdtlb_expect_substring "resource not available" $response

    return [ocd_test_pass]
}

return [run_test]
