echo "Hello? (Hello? Hello? Hello?)"
echo "Is there anybody in there?"
echo "Just nod if you can hear me"
echo "Is there anyone home?"
echo "Come on now"
echo "I hear you're feeling down"
echo "Well I can ease your pain"
echo "Get you on your feet again"
echo "Relax"
echo "I'll need some information first"
echo "Just the basic facts"
echo "Can you show me where it hurts?"
