#!/usr/bin/expect

set STAND_NAME [lindex $argv 0]
set PLATFORM [lindex $argv 1]

proc try_to_instantiate_bitstream {STAND_NAME PLATFORM} {
  catch {system killall -9 openocd}
  catch {system killall -9 vivado_lab}
  catch {system killall -9 hw_server}
  catch {system rm /home/stand/hw_server.log}

  system /home/stand/hw_server.sh

  set timeout 120

  set REMOTE_PREFIX remote:
  if {[string first $REMOTE_PREFIX $PLATFORM] == 0} {
    set PLATFORM [string range $PLATFORM [string length $REMOTE_PREFIX] end]
  }

  # check if platform starts with "/"
  if {[string first / $PLATFORM] == 0} {
    set EXPECTED_PATTERN "Flashing bitstream completed!"
    spawn [pwd]/fpga.sh bit $STAND_NAME $PLATFORM
  } else {
    set EXPECTED_PATTERN "Setting platform completed!"
    spawn [pwd]/fpga.sh set $STAND_NAME $PLATFORM
  }

  expect {
    $EXPECTED_PATTERN {
      puts "bitstream instantiated!"
    }
    eof {
      error "unexpected EOF (waiting for device programming)"
    }
    timeout {
      error "unexpected timeout (waiting for device programming)"
    }
  }
}

set MAX_ATTEMPTS 3
for { set attempt_num 1 } { $attempt_num <= $MAX_ATTEMPTS } { incr attempt_num } {
  puts "attempting to instantiate bitstream, attempt $attempt_num"
  if {![catch {try_to_instantiate_bitstream $STAND_NAME $PLATFORM} err]} {
    puts "bitstream successfully instantiated"
    return
  }
  puts "could not instantiate bitstream: $err"
}

error "$MAX_ATTEMPTS attempts to instantiate bitstream failed"
