proc run_test {} {
  global FPR

  set target_no_fp [expr [target_info cpu,has_floats] == 0]

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "fp_access_when_disabled.S" "$default_bin_prefix.exe"

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"
  ocdtlb_run_expect "reg $FPR(0)" $target_no_fp

  return [ocd_test_pass]
}

return [run_test]

