if {[expr [target_info cpu,xlen] != 64]} { return [ocd_test_unsupported] }
if {![target_info memory,has_high_pa]} { return [ocd_test_unsupported] }

# This test attempts to write and then read <count> of elements (<name>: b/h/w)
# with last element being written and read from last address (2^64 - <size>)
# First, zeros are written to be shure that memory content has actually changed
# after write

ocd_compile_executable "special.S" "$default_bin_prefix.exe"

ocd_connect

ocdtlb_run_expect "reset halt"

proc get_splat {count value} {
  if {$count eq ""} {
    return [list $value]
  }
  return [lrepeat $count $value]
}

proc write_and_read {name address count value} {
  ocdtlb_run_expect "mw$name $address $value $count"
  set response [ocdtlb_rsp_get [ocdtlb_run_expect "md$name $address $count"] data]
  ocdtlb_expect_equal $response [get_splat $count $value]
}

proc test_one_case {name size count} {
  set END_ADDR "0xffffffffffffffff"
  if {$count eq ""} {
    set address [expr ($END_ADDR - $size) + 1]
  } else {
    set address [expr ($END_ADDR - $size * $count) + 1]
  }

  write_and_read $name $address $count 0
  write_and_read $name $address $count 0xa
}

foreach count {"" 1 2} {
  dict for {name size} [dict create "b" 1 "h" 2 "w" 4 "d" 8] {
    test_one_case $name $size $count
  }
}

ocd_test_pass
