# This was ocd.basic/mem_mdx.exp. Since this test works, it is not to be
# modified. It shall lie here and rot until the end of times.

proc run_test {} {
  set xlen64 [expr [target_info cpu,xlen] == 64]

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "special.S" "$default_bin_prefix.exe"

  # created by compile executable
  set MEM_ADDR [tool_state_get_program_symbol work_area_start]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "mwb $MEM_ADDR 42"
  ocdtlb_do_byte_read_compare $MEM_ADDR [list 42]

  ocdtlb_run_expect "mwh $MEM_ADDR 0xbad0"
  ocdtlb_do_byte_read_compare $MEM_ADDR [list 0xd0 0xba]

  ocdtlb_run_expect "mww $MEM_ADDR 0xfffafbfc"
  ocdtlb_do_byte_read_compare $MEM_ADDR [list 0xfc 0xfb 0xfa 0xff]

  if {$xlen64} {
    ocdtlb_run_expect "mwd $MEM_ADDR 0xC00010FFB0BAB0BA"
    ocdtlb_do_byte_read_compare $MEM_ADDR [list 0xba 0xb0 0xba 0xb0 0xff 0x10 0x00 0xc0]
  }

  return [ocd_test_pass]
}

return [run_test]

