proc run_test {} {
  global ra
  global perror_threshold

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "step_linkreg_clobber.S" "$default_bin_prefix.exe"

  # created by compile executable
  set ENTRY_ADDR [tool_state_get_program_symbol _entry]
  set MAIN_ADDR [tool_state_get_program_symbol main]
  set END_ADDR [tool_state_get_program_symbol end1]
  set BRN_ADDR [tool_state_get_program_symbol brn]
  set EXPECTED_LINK [tool_state_get_program_symbol link]

  set xlen64 [expr [target_info cpu,xlen] == 64]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "load_image $default_bin_prefix.exe"
  ocdtlb_run_expect "reg pc $ENTRY_ADDR"

  ocdtlb_do_expect_step_until $BRN_ADDR 500

  set pc_before_step [ocdtlb_rsp_get [ocdtlb_run_expect "reg pc"]]
  ocdtlb_run_expect "step"
  set pc_after_step [ocdtlb_rsp_get [ocdtlb_run_expect "reg pc"]]
  set link_reg [ocdtlb_rsp_get [ocdtlb_run_expect "reg $ra"]]

  verbose "pc_before: $pc_before_step, pc_after: $pc_after_step" 1
  verbose "link_reg: $link_reg, expected_reg: $EXPECTED_LINK" 1

  if {[lindex [split [target_info cpu,name] "_"] 0] eq "scr6"} {
    setup_kfail openocd_EMBARGO/20318 "*-*-*"
    set perror_threshold 2
  }

  if {![ocdtlb_compare_equal_hex $link_reg $EXPECTED_LINK]} {
    perror "link register $link_reg is not equal to the expected value $EXPECTED_LINK"
    return [ocd_test_fail]
  }

  if {![ocdtlb_compare_equal_hex $pc_after_step $END_ADDR]} {
    perror "pc after jalr $pc_after_step is not equal to the expected value $END_ADDR"
    return [ocd_test_fail]
  }

  return [ocd_test_pass]
}

return [run_test]

