proc run_test {} {

  set default_bin_prefix [tool_state_get default_bin_prefix]
  ocd_compile_executable "wp_on_byte.S" "$default_bin_prefix.exe"

  set ENTRY_ADDR [tool_state_get_program_symbol _entry]

  ocd_connect

  ocdtlb_run_expect "targets 0"
  ocdtlb_run_expect "reset halt"

  ocdtlb_run_expect "wp $ENTRY_ADDR 4 a 0" expect_failure
  ocdtlb_run_expect "wp $ENTRY_ADDR 4 a 1" expect_failure
  ocdtlb_run_expect "wp $ENTRY_ADDR 4 a 1 0xff" expect_failure
  ocdtlb_run_expect "wp $ENTRY_ADDR 4 a 1 0xffffffffffffffff"
  ocdtlb_run_expect "rwp $ENTRY_ADDR"
  return [ocd_test_pass]
}

return [run_test]
